(() => {
  'use strict';

  const STORAGE_KEY = 'bento.app.state.v1';
  const VERSION = 2;
  const MEAL_SLOTS = ['breakfast', 'lunch', 'dinner', 'snack'];
  const THEMES = {
    blossom:{label:'Blossom',accent:'#f28aa4',strong:'#df6787',soft:'#ffd9e2',bg:'#fff8f5',surface2:'#fff1f0'},
    peach:{label:'Peach',accent:'#ef9b7b',strong:'#d77d5f',soft:'#ffe0d3',bg:'#fff9f4',surface2:'#fff0e8'},
    matcha:{label:'Matcha',accent:'#8eaa7d',strong:'#6f8d61',soft:'#dce8d6',bg:'#fbfaf5',surface2:'#f0f5eb'},
    lavender:{label:'Lavender',accent:'#b79bd4',strong:'#9274b2',soft:'#eadff4',bg:'#fcf9ff',surface2:'#f4eef9'},
    sakura:{label:'Sakura',accent:'#f4a9bb',strong:'#dc7894',soft:'#fde0e7',bg:'#fffafc',surface2:'#fff0f4'}
  };

  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const uid = (p='id') => `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
  const esc = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const clamp = (n,min,max) => Math.min(max,Math.max(min,n));
  const debounce = (fn,ms=100) => { let t; return (...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),ms)}; };

  function defaultState(){return{
    version:VERSION,recipes:[],pantry:[],grocery:[],mealPlan:{},history:[],leftovers:[],bentos:[],
    stats:{rescuedCount:0},
    settings:{displayName:'',defaultServings:2,units:'metric',weekStart:'monday',diet:'',allergies:'',equipment:'',theme:'blossom',weeklyGoal:4},
    goals:{cookPerWeek:4,newPerMonth:2,rescuePerMonth:3}
  }}

  function normalizeState(raw){
    const base=defaultState();
    if(!raw || typeof raw!=='object') return base;
    const s={...base,...raw};
    for(const k of ['recipes','pantry','grocery','history','leftovers','bentos']) if(!Array.isArray(s[k])) s[k]=[];
    if(!s.mealPlan || typeof s.mealPlan!=='object' || Array.isArray(s.mealPlan)) s.mealPlan={};
    s.settings={...base.settings,...(raw.settings||{})};
    s.goals={...base.goals,...(raw.goals||{})};
    s.stats={...base.stats,...(raw.stats||{})};
    s.version=VERSION;
    s.recipes=s.recipes.map(r=>({...r,energy:r.energy||'normal',cleanup:Number(r.cleanup)||2,freezer:r.freezer||'no',equipment:r.equipment||'',source:r.source||''}));
    s.pantry=s.pantry.map(p=>({...p,opened:p.opened||'',packageSize:p.packageSize||'',store:p.store||''}));
    return s;
  }

  function loadState(){try{return normalizeState(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return defaultState()}}
  let state=loadState();
  let currentView='home', previousView='home', weekOffset=0, recipeFilter='All', pantryFilter='All', pantrySort='expiry', matchFilter='all', activeSmartTool='roulette';
  let deferredInstallPrompt=null, wakeLock=null, cookingTimer=null, timerSeconds=0, cookingSession=null;
  let persistTimer=null, renderRAF=null, renderRequested=false;

  function persistNow(){
    clearTimeout(persistTimer); persistTimer=null;
    try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(err){console.error(err);toast('Storage is full. Export a backup and remove old data/photos.');}
  }
  function queuePersist(){clearTimeout(persistTimer);persistTimer=setTimeout(persistNow,70)}
  function commit(render=true){queuePersist();if(render)scheduleRender()}
  function scheduleRender(){renderRequested=true;if(renderRAF)return;renderRAF=requestAnimationFrame(()=>{renderRAF=null;if(renderRequested){renderRequested=false;renderCurrentView();renderGlobalBadges();}})}

  function toast(msg){const n=$('#toast');if(!n)return;n.textContent=msg;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),1800)}
  function dateKey(date){const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function parseDate(str){return str?new Date(`${str}T12:00:00`):null}
  function daysUntil(str){if(!str)return Infinity;const t=new Date();t.setHours(0,0,0,0);const d=new Date(`${str}T00:00:00`);return Math.ceil((d-t)/86400000)}
  function startOfWeek(baseDate=new Date(),offset=weekOffset){const d=new Date(baseDate.getFullYear(),baseDate.getMonth(),baseDate.getDate());const day=d.getDay();const diff=state.settings.weekStart==='sunday'?-day:(day===0?-6:1-day);d.setDate(d.getDate()+diff+offset*7);return d}
  function weekDates(offset=weekOffset){const s=startOfWeek(new Date(),offset);return Array.from({length:7},(_,i)=>{const d=new Date(s);d.setDate(s.getDate()+i);return d})}
  function formatShortDate(d){return d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
  function formatLongDate(d){return d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
  function formatDateTime(iso){return new Date(iso).toLocaleString(undefined,{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}
  function applyTheme(){const t=THEMES[state.settings.theme]||THEMES.blossom,r=document.documentElement.style;r.setProperty('--accent',t.accent);r.setProperty('--accent-strong',t.strong);r.setProperty('--accent-soft',t.soft);r.setProperty('--bg',t.bg);r.setProperty('--surface-2',t.surface2);$('meta[name="theme-color"]')?.setAttribute('content',t.accent)}

  function ingredientName(line){return String(line||'').toLowerCase().replace(/\([^)]*\)/g,' ').replace(/^\s*[\d¼½¾⅓⅔⅛⅜⅝⅞.,/\-]+\s*/u,'').replace(/^\s*(cups?|tbsp|tablespoons?|tsp|teaspoons?|grams?|g|kg|ml|l|liters?|litres?|oz|ounces?|lbs?|pounds?|pcs?|pieces?|cans?|packs?|slices?|cloves?|heads?|bunch(?:es)?|pinch(?:es)?|dash(?:es)?)\b\s*/i,'').replace(/\b(chopped|diced|minced|sliced|optional|divided|to taste|for serving|fresh|frozen)\b/g,' ').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim()}
  function ingredientMatches(a,b){const x=ingredientName(a),y=ingredientName(b);if(!x||!y)return false;return x===y||x.includes(y)||y.includes(x)||x.split(' ').some(w=>w.length>3&&y.includes(w))}
  function groceryCategory(text){const s=ingredientName(text);if(/apple|banana|berry|strawber|lemon|lime|orange|tomato|onion|garlic|carrot|cabbage|spinach|lettuce|broccoli|pepper|potato|mushroom|cucumber|ginger|scallion|green onion|herb/.test(s))return'Produce';if(/chicken|beef|pork|fish|salmon|tuna|shrimp|tofu|egg/.test(s))return'Protein';if(/milk|cream|cheese|butter|yogurt/.test(s))return'Dairy & Eggs';if(/rice|flour|sugar|salt|oil|sauce|vinegar|noodle|pasta|bread|crumb|miso|nori|spice|stock|broth/.test(s))return'Pantry';return'Other'}
  function getRecipe(id){return state.recipes.find(r=>r.id===id)}
  function totalTime(r){return Number(r?.prep||0)+Number(r?.cook||0)}
  function foodEmoji(r){const s=`${r?.title||''} ${r?.category||''} ${r?.cuisine||''}`.toLowerCase();if(/dessert|cake|mochi|daifuku|sweet/.test(s))return'🍡';if(/soup|ramen|miso/.test(s))return'🍜';if(/rice|bento|don|onigiri/.test(s))return'🍱';if(/breakfast|egg|omelet|omelette/.test(s))return'🍳';if(/salad|vegetarian|veggie|side/.test(s))return'🥗';if(/fish|salmon|tuna/.test(s))return'🐟';if(/drink|tea|coffee/.test(s))return'🍵';return'🍽️'}
  function pantryEmoji(p){const s=(p?.name||'').toLowerCase();if(/egg/.test(s))return'🥚';if(/milk/.test(s))return'🥛';if(/rice/.test(s))return'🍚';if(/fruit|apple|berry|straw/.test(s))return'🍓';if(/veget|carrot|broccoli|onion|cabbage|spinach/.test(s))return'🥕';if(/chicken|meat|beef|pork/.test(s))return'🍗';if(/fish|salmon|tuna/.test(s))return'🐟';return'🥫'}
  function emptyCard(text,btn='',action=''){return `<div class="empty-card">${esc(text)}${btn?`<br><button data-action="${action}">${esc(btn)}</button>`:''}</div>`}
  function countCooked(recipeId,days=Infinity){const cutoff=Number.isFinite(days)?Date.now()-days*86400000:0;return state.history.filter(h=>h.recipeId===recipeId&&new Date(h.date).getTime()>=cutoff).length}

  function navigate(view,pushHash=true){if(!document.querySelector(`.view[data-view="${view}"]`))view='home';if(currentView!==view)previousView=currentView;currentView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));if(pushHash)history.replaceState(null,'',`#${view}`);window.scrollTo(0,0);$('#mainContent')?.focus({preventScroll:true});renderCurrentView();renderGlobalBadges()}
  function back(){navigate(previousView==='more'?'more':previousView||'home')}

  function renderGlobalBadges(){
    const unchecked=state.grocery.reduce((n,g)=>n+(!g.checked?1:0),0);
    if($('#groceryCountQuick'))$('#groceryCountQuick').textContent=`${unchecked} item${unchecked===1?'':'s'}`;
    if($('#pantryCountQuick'))$('#pantryCountQuick').textContent=`${state.pantry.length} item${state.pantry.length===1?'':'s'}`;
  }
  function renderGreeting(){const h=new Date().getHours(),g=h<12?'Good morning':h<18?'Good afternoon':'Good evening',name=(state.settings.displayName||'').trim();$('#greetingText').textContent=`${g}${name?`, ${name}`:''} ✿`}
  function renderHome(){
    renderGreeting();
    const today=dateKey(new Date()),plan=state.mealPlan[today]||{};
    $('#todayMeals').innerHTML=MEAL_SLOTS.map(slot=>{const item=plan[slot];let title='Nothing planned',sub='Tap to add';if(item?.recipeId){const r=getRecipe(item.recipeId);if(r){title=r.title;sub=`${totalTime(r)} min · ${item.servings||r.servings||2} servings`}}else if(item?.custom){title=item.custom;sub=item.prepNote||'Custom meal'}return `<button class="meal-card" data-meal-date="${today}" data-meal-slot="${slot}"><span class="meal-slot">${slot}</span><span class="meal-main"><b>${esc(title)}</b><small>${esc(sub)}</small></span><span class="arrow">›</span></button>`}).join('');
    const weekMeals=weekDates(0).reduce((n,d)=>n+Object.keys(state.mealPlan[dateKey(d)]||{}).length,0);
    const expiring=state.pantry.filter(p=>{const d=daysUntil(p.expiry);return d>=0&&d<=3}).length;
    const monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0);const cookedMonth=state.history.filter(h=>new Date(h.date)>=monthStart).length;
    $('#homeStats').innerHTML=`<div class="stat-card"><strong>${weekMeals}</strong><small>meals planned</small></div><div class="stat-card"><strong>${cookedMonth}</strong><small>cooked this month</small></div><div class="stat-card"><strong>${expiring}</strong><small>use soon</small></div>`;
    renderAttention();
    const favs=state.recipes.filter(r=>r.favorite).slice(0,6);$('#homeFavorites').innerHTML=favs.length?favs.map(recipeMini).join(''):emptyCard('Heart recipes you love and they’ll appear here.','Browse recipes','go-recipes');
  }
  function renderAttention(){const expiring=state.pantry.filter(p=>{const d=daysUntil(p.expiry);return d>=0&&d<=3}).sort((a,b)=>daysUntil(a.expiry)-daysUntil(b.expiry));const low=state.pantry.filter(p=>p.lowStock),unchecked=state.grocery.filter(g=>!g.checked).length,leftSoon=state.leftovers.filter(l=>{const d=daysUntil(l.useBy);return d>=0&&d<=2}).length;const c=[];if(expiring.length)c.push(`<button class="attention-card" data-view-link="smart" data-auto-tool="rescue"><span class="dot"></span><div><b>${expiring.length} pantry item${expiring.length>1?'s':''} expiring soon</b><small>${esc(expiring.slice(0,3).map(x=>x.name).join(', '))}</small></div><span>›</span></button>`);if(leftSoon)c.push(`<button class="attention-card" data-view-link="leftovers"><span class="dot"></span><div><b>${leftSoon} leftover${leftSoon>1?'s':''} to use soon</b><small>Eat, freeze or plan them next</small></div><span>›</span></button>`);if(low.length)c.push(`<button class="attention-card" data-nav="pantry"><span class="dot"></span><div><b>${low.length} low-stock item${low.length>1?'s':''}</b><small>Restock when convenient</small></div><span>›</span></button>`);if(unchecked)c.push(`<button class="attention-card" data-view-link="grocery"><span class="dot"></span><div><b>${unchecked} grocery item${unchecked>1?'s':''} waiting</b><small>Open your shopping list</small></div><span>›</span></button>`);$('#attentionCards').innerHTML=c.join('')||emptyCard('Nothing urgent right now. Your kitchen is looking tidy ✿')}
  function recipeMini(r){return `<button class="mini-recipe" data-recipe-id="${r.id}"><b>${foodEmoji(r)} ${esc(r.title)}</b><small>${totalTime(r)} min · ${esc(r.category||'Other')}</small></button>`}

  function renderPlan(){const dates=weekDates(),todayKey=dateKey(new Date());$('#weekLabel').textContent=`${formatShortDate(dates[0])} – ${formatShortDate(dates[6])}`;$('#weekDays').innerHTML=dates.map(d=>`<div class="day-pill ${dateKey(d)===todayKey?'today':''}"><b>${d.toLocaleDateString(undefined,{weekday:'short'})}</b><span>${d.getDate()}</span></div>`).join('');$('#mealPlanGrid').innerHTML=dates.map(d=>{const key=dateKey(d),p=state.mealPlan[key]||{};return `<article class="plan-day"><div class="plan-day-head"><b>${esc(formatLongDate(d))}</b><small>${key===todayKey?'Today':''}</small></div>${MEAL_SLOTS.map(slot=>{const item=p[slot];let main='Add meal',sub='';if(item?.recipeId){const r=getRecipe(item.recipeId);if(r){main=r.title;sub=`${totalTime(r)} min${item.prepNote?` · ${item.prepNote}`:''}${item.planLeftovers?' · + leftovers':''}`}}else if(item?.custom){main=item.custom;sub=item.prepNote||'Custom meal'}return `<button class="plan-slot" data-meal-date="${key}" data-meal-slot="${slot}"><span>${slot}</span><div><b>${esc(main)}</b>${sub?`<small>${esc(sub)}</small>`:''}</div><i class="plan-add">${item?'›':'+'}</i></button>`}).join('')}</article>`}).join('')}

  function recipeCard(r){return `<article class="recipe-card"><button class="heart-btn" data-favorite="${r.id}" aria-label="Favorite">${r.favorite?'♥':'♡'}</button><button class="recipe-open" data-recipe-id="${r.id}"><div class="thumb">${foodEmoji(r)}</div><div class="body"><b>${esc(r.title)}</b><small>${totalTime(r)} min · ${r.servings||2} servings · ${r.cleanup===1?'1 pan':r.cleanup===3?'project':'easy cleanup'}</small><div class="badge-row"><span class="badge">${esc(r.category||'Other')}</span>${r.cuisine?`<span class="badge">${esc(r.cuisine)}</span>`:''}${r.collection?`<span class="badge">${esc(r.collection)}</span>`:''}${r.freezer==='yes'?'<span class="badge">❄ freezer</span>':''}</div></div></button></article>`}
  function renderRecipeFilters(){const cats=['All','Favorites','Quick','Low Cleanup','Freezer Friendly',...[...new Set(state.recipes.map(r=>r.category).filter(Boolean))]];$('#recipeFilters').innerHTML=cats.map(c=>`<button class="chip ${recipeFilter===c?'active':''}" data-recipe-filter="${esc(c)}">${esc(c)}</button>`).join('')}
  function filteredRecipes(){const q=($('#recipeSearch')?.value||'').trim().toLowerCase();let list=[...state.recipes];if(recipeFilter==='Favorites')list=list.filter(r=>r.favorite);else if(recipeFilter==='Quick')list=list.filter(r=>totalTime(r)<=30);else if(recipeFilter==='Low Cleanup')list=list.filter(r=>Number(r.cleanup||2)<=1);else if(recipeFilter==='Freezer Friendly')list=list.filter(r=>r.freezer==='yes');else if(recipeFilter.startsWith('Collection:'))list=list.filter(r=>(r.collection||'')===recipeFilter.slice(11));else if(recipeFilter!=='All')list=list.filter(r=>r.category===recipeFilter);if(q)list=list.filter(r=>`${r.title} ${r.cuisine} ${r.category} ${r.collection} ${(r.ingredients||[]).join(' ')} ${r.notes||''} ${r.equipment||''}`.toLowerCase().includes(q));const sort=$('#recipeSort')?.value||'newest';if(sort==='name')list.sort((a,b)=>a.title.localeCompare(b.title));else if(sort==='quick')list.sort((a,b)=>totalTime(a)-totalTime(b));else if(sort==='favorite')list.sort((a,b)=>Number(b.favorite)-Number(a.favorite)||a.title.localeCompare(b.title));else if(sort==='cooked')list.sort((a,b)=>countCooked(b.id)-countCooked(a.id));else list.sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));return list}
  function renderRecipes(){renderRecipeFilters();const list=filteredRecipes();$('#recipeGrid').innerHTML=list.length?list.map(recipeCard).join(''):emptyCard(state.recipes.length?'No recipes match this search.':'Your recipe book is empty. Add your first recipe to begin.','Add recipe','add-recipe');if($('#favoritesGrid')){const f=state.recipes.filter(r=>r.favorite);$('#favoritesGrid').innerHTML=f.length?f.map(recipeCard).join(''):emptyCard('No favorites yet. Tap ♡ on a recipe you love.','Browse recipes','go-recipes')}}

  function renderPantry(){const opts=['All','Expiring Soon','Low Stock','Fridge','Freezer','Pantry','Spice Rack','Other'];$('#pantryFilters').innerHTML=opts.map(c=>`<button class="chip ${pantryFilter===c?'active':''}" data-pantry-filter="${esc(c)}">${esc(c)}</button>`).join('');const q=($('#pantrySearch')?.value||'').trim().toLowerCase();let list=state.pantry.filter(p=>!q||`${p.name} ${p.location} ${p.store||''}`.toLowerCase().includes(q));if(pantryFilter==='Expiring Soon')list=list.filter(p=>{const d=daysUntil(p.expiry);return d>=0&&d<=5});else if(pantryFilter==='Low Stock')list=list.filter(p=>p.lowStock);else if(pantryFilter!=='All')list=list.filter(p=>p.location===pantryFilter);if(pantrySort==='expiry')list.sort((a,b)=>(daysUntil(a.expiry)-daysUntil(b.expiry))||a.name.localeCompare(b.name));else list.sort((a,b)=>a.name.localeCompare(b.name));$('#pantrySortButton').textContent=pantrySort==='expiry'?'Expiry':'A–Z';$('#pantryList').innerHTML=list.length?list.map(p=>{const due=daysUntil(p.expiry);let status='';if(Number.isFinite(due)){if(due<0)status='<span class="status-pill warn">Expired</span>';else if(due<=3)status=`<span class="status-pill warn">${due===0?'Today':`${due}d left`}</span>`;else status=`<span class="status-pill">${due}d left</span>`}if(p.lowStock)status+='<span class="status-pill warn">Low stock</span>';if(p.staple)status+='<span class="status-pill">Staple</span>';return `<button class="list-card" data-pantry-id="${p.id}"><span class="emoji">${pantryEmoji(p)}</span><span class="content"><b>${esc(p.name)}</b><small>${esc(`${p.quantity??''} ${p.unit||''}`.trim()||'Quantity not set')} · ${esc(p.location)}${p.opened?` · opened ${esc(p.opened)}`:''}</small>${status}</span><span class="meta">›</span></button>`}).join(''):emptyCard(state.pantry.length?'No pantry items match this filter.':'Your pantry is empty. Add what you already have at home.','Add pantry item','add-pantry')}

  function grocerySourceLabel(g){if(!g.source)return'';if(g.source.startsWith('recipe:')){const r=getRecipe(g.source.slice(7));return r?`For ${r.title}`:''}if(g.source==='week-plan')return'From meal plan';if(g.source==='low-stock')return'Low stock';return''}
  function renderGrocery(){const unchecked=state.grocery.filter(g=>!g.checked).length,checked=state.grocery.length-unchecked,estimate=state.grocery.reduce((n,g)=>n+(Number(g.price)||0),0);$('#groceryUnchecked').textContent=unchecked;$('#groceryChecked').textContent=checked;$('#groceryEstimate').textContent=estimate?estimate.toLocaleString(undefined,{style:'currency',currency:'PHP'}):'—';const groups={};[...state.grocery].sort((a,b)=>Number(a.checked)-Number(b.checked)||(a.text||'').localeCompare(b.text||'')).forEach(g=>{const cat=g.category||groceryCategory(g.text);(groups[cat]||=[]).push(g)});const order=['Produce','Protein','Dairy & Eggs','Pantry','Other'];$('#groceryList').innerHTML=state.grocery.length?order.filter(k=>groups[k]?.length).map(cat=>`<section class="grocery-group"><h3>${cat}</h3>${groups[cat].map(g=>`<div class="grocery-item ${g.checked?'checked':''}"><input type="checkbox" data-grocery-check="${g.id}" ${g.checked?'checked':''} aria-label="Check ${esc(g.text)}"><span>${esc(g.text)}${grocerySourceLabel(g)?`<small class="muted"> · ${esc(grocerySourceLabel(g))}</small>`:''}</span><button data-grocery-delete="${g.id}" aria-label="Delete">×</button></div>`).join('')}</section>`).join(''):emptyCard('Your grocery list is empty. Add an item or generate one from this week’s meal plan.')}

  function pantryAvailableNames(extra=[]){return [...state.pantry.map(p=>p.name),...extra].filter(Boolean)}
  function expiringIngredientNames(){return state.pantry.filter(p=>{const d=daysUntil(p.expiry);return d>=0&&d<=4}).map(p=>p.name)}
  function recipeMatch(recipe,extra=[]){const avail=pantryAvailableNames(extra),ings=(recipe.ingredients||[]).filter(Boolean),missing=ings.filter(i=>!avail.some(a=>ingredientMatches(i,a))),matched=ings.length-missing.length,useSoon=ings.filter(i=>expiringIngredientNames().some(a=>ingredientMatches(i,a))).length;return{matched,total:ings.length,missing,percent:ings.length?Math.round(matched/ings.length*100):0,useSoon}}
  function renderCookMatches(){const extras=($('#customCookIngredients')?.value||'').split(',').map(s=>s.trim()).filter(Boolean);let results=state.recipes.map(r=>({recipe:r,...recipeMatch(r,extras)}));if(matchFilter==='perfect')results=results.filter(x=>x.missing.length===0);else if(matchFilter==='almost')results=results.filter(x=>x.missing.length<=2);else if(matchFilter==='use-soon')results=results.filter(x=>x.useSoon>0);results.sort((a,b)=>b.useSoon-a.useSoon||b.percent-a.percent||a.missing.length-b.missing.length||totalTime(a.recipe)-totalTime(b.recipe));$('#cookMatchList').innerHTML=results.length?results.map(x=>`<article class="match-card"><div class="match-card-head"><div><b>${foodEmoji(x.recipe)} ${esc(x.recipe.title)}</b><small class="muted">${x.matched}/${x.total} available · ${totalTime(x.recipe)} min${x.useSoon?` · rescues ${x.useSoon}`:''}</small></div><strong>${x.percent}%</strong></div><div class="match-bar"><i style="width:${x.percent}%"></i></div><div class="missing">${x.missing.length?`Missing: ${esc(x.missing.join(', '))}`:'Perfect match — you have everything listed.'}</div><div class="action-row" style="margin-top:10px;margin-bottom:0"><button class="soft-btn" data-recipe-id="${x.recipe.id}">View</button>${x.missing.length?`<button class="soft-btn" data-add-missing="${x.recipe.id}">Add missing</button>`:''}</div></article>`).join(''):emptyCard(state.recipes.length?'No recipes match this filter.':'Add some recipes first, then Bento can match them to your pantry.','Add recipe','add-recipe')}

  function smartFilteredRecipes(){const max=Number($('#smartTime')?.value||0),energy=$('#smartEnergy')?.value||'any',equipment=$('#smartEquipment')?.value||'any';return state.recipes.filter(r=>(!max||totalTime(r)<=max)&&(energy==='any'||r.energy===energy)&&(equipment==='any'||(equipment==='none'?!((r.equipment||'').trim()):(r.equipment||'').toLowerCase().includes(equipment))))}
  function smartRecipeResult(title,list,empty='No recipes match those settings yet.'){return `<div class="smart-card"><h3>${esc(title)}</h3>${list.length?list.slice(0,8).map(r=>`<button class="list-card" data-recipe-id="${r.id}"><span class="emoji">${foodEmoji(r)}</span><span class="content"><b>${esc(r.title)}</b><small>${totalTime(r)} min · ${r.cleanup===1?'1 pan':'cleanup '+r.cleanup}/3 · ${r.energy} effort</small></span><span class="meta">›</span></button>`).join(''):`<p class="muted">${esc(empty)}</p>`}</div>`}
  function recipeOptions(selected=''){return `<option value="">Choose recipe…</option>`+[...state.recipes].sort((a,b)=>a.title.localeCompare(b.title)).map(r=>`<option value="${r.id}" ${r.id===selected?'selected':''}>${esc(r.title)}</option>`).join('')}
  function renderSmart(){$$('[data-smart-tool]').forEach(b=>b.classList.toggle('active',b.dataset.smartTool===activeSmartTool));const box=$('#smartResult');if(!state.recipes.length && !['prep','batch','three'].includes(activeSmartTool)){box.innerHTML=emptyCard('Add recipes first so Kitchen Magic has something to work with.','Add recipe','add-recipe');return}const filtered=smartFilteredRecipes();
    if(activeSmartTool==='roulette'){const pick=filtered.length?filtered[Math.floor(Math.random()*filtered.length)]:null;box.innerHTML=pick?`<div class="smart-card"><p class="eyebrow">Bento picked</p><h3>${foodEmoji(pick)} ${esc(pick.title)}</h3><p class="muted">${totalTime(pick)} min · ${pick.energy} effort · cleanup ${pick.cleanup}/3</p><div class="action-row" style="margin-top:12px"><button class="primary-btn" data-recipe-id="${pick.id}">Open recipe</button><button class="soft-btn" data-smart-reroll>Roll again 🎲</button></div></div>`:smartRecipeResult('Bento Roulette',[]);return}
    if(activeSmartTool==='lazy'){const list=filtered.filter(r=>r.energy==='low'||Number(r.cleanup||2)===1||totalTime(r)<=20).sort((a,b)=>Number(a.cleanup)-Number(b.cleanup)||totalTime(a)-totalTime(b));box.innerHTML=smartRecipeResult('Low-effort picks',list,'Add energy/cleanup details to recipes to make this smarter.');return}
    if(activeSmartTool==='rescue'){const exp=expiringIngredientNames();const list=filtered.map(r=>({r,m:recipeMatch(r)})).filter(x=>x.m.useSoon>0).sort((a,b)=>b.m.useSoon-a.m.useSoon||b.m.percent-a.m.percent);box.innerHTML=`<div class="smart-card"><h3>🧊 Fridge Rescue</h3><p class="muted">Use soon: ${esc(exp.join(', ')||'Nothing is expiring soon.')}</p>${list.length?list.slice(0,8).map(x=>`<button class="list-card" data-recipe-id="${x.r.id}"><span class="emoji">${foodEmoji(x.r)}</span><span class="content"><b>${esc(x.r.title)}</b><small>Uses ${x.m.useSoon} expiring item${x.m.useSoon>1?'s':''} · ${x.m.percent}% pantry match</small></span><span class="meta">›</span></button>`).join(''):'<p class="muted" style="margin-top:10px">No saved recipe currently uses the expiring ingredients.</p>'}</div>`;return}
    if(activeSmartTool==='complete'){box.innerHTML=`<div class="smart-card"><h3>🥗 Complete My Meal</h3><p class="muted">Choose your main and Bento will suggest complementary saved recipes.</p><div class="input-prompt"><select id="completeRecipeSelect">${recipeOptions()}</select><button data-complete-meal>Complete</button></div><div id="completeMealOutput"></div></div>`;return}
    if(activeSmartTool==='deadline'){const now=new Date();now.setHours(19,0,0,0);box.innerHTML=`<div class="smart-card"><h3>⏰ Dinner Deadline</h3><p class="muted">Tell Bento when food should be ready and it will work backward.</p><div class="input-prompt"><select id="deadlineRecipeSelect">${recipeOptions()}</select><input id="deadlineTime" type="time" value="19:00"><button data-deadline-build>Plan</button></div><div id="deadlineOutput"></div></div>`;return}
    if(activeSmartTool==='prep'){const today=state.mealPlan[dateKey(new Date())]||{},recipes=MEAL_SLOTS.map(s=>getRecipe(today[s]?.recipeId)).filter(Boolean),notes=MEAL_SLOTS.map(s=>today[s]?.prepNote).filter(Boolean),all=[...new Set(recipes.flatMap(r=>(r.ingredients||[]).map(ingredientName)).filter(Boolean))];box.innerHTML=`<div class="smart-card"><h3>🔪 Mise en Place</h3>${recipes.length?`<p class="muted">For today's ${recipes.length} saved recipe${recipes.length>1?'s':''}.</p><div class="detail-section"><h3>Prep ingredients</h3>${all.slice(0,30).map(x=>`<div class="ingredient-line">○ ${esc(x)}</div>`).join('')}</div>${notes.length?`<div class="detail-section"><h3>Prep notes</h3>${notes.map(n=>`<div class="ingredient-line">○ ${esc(n)}</div>`).join('')}</div>`:''}`:'<p class="muted">Plan at least one saved recipe today to create a prep list.</p>'}</div>`;return}
    if(activeSmartTool==='batch'){const recipes=[];weekDates().forEach(d=>Object.values(state.mealPlan[dateKey(d)]||{}).forEach(i=>{const r=getRecipe(i?.recipeId);if(r)recipes.push(r)}));const map=new Map();recipes.forEach(r=>(r.ingredients||[]).forEach(line=>{const n=ingredientName(line);if(!n)return;const o=map.get(n)||{count:0,recipes:new Set()};o.count++;o.recipes.add(r.title);map.set(n,o)}));const overlaps=[...map.entries()].filter(([,v])=>v.recipes.size>=2).sort((a,b)=>b[1].recipes.size-a[1].recipes.size);box.innerHTML=`<div class="smart-card"><h3>🥘 Batch Prep</h3>${overlaps.length?`<p class="muted">Prep these once and use them across multiple meals this week.</p>${overlaps.slice(0,20).map(([name,v])=>`<div class="list-card"><span class="emoji">🔪</span><span class="content"><b>${esc(name)}</b><small>${esc([...v.recipes].join(' · '))}</small></span><span class="meta">×${v.recipes.size}</span></div>`).join('')}`:'<p class="muted">Plan more than one recipe this week to find overlapping prep.</p>'}</div>`;return}
    if(activeSmartTool==='three'){box.innerHTML=`<div class="smart-card"><h3>🧩 3-Ingredient Challenge</h3><p class="muted">Enter up to three ingredients. Bento ranks recipes by how many they use.</p><div class="input-prompt"><input id="threeIngredientsInput" placeholder="eggs, rice, carrots"><button data-three-match>Find</button></div><div id="threeOutput"></div></div>`;return}
  }

  function renderBentoBuilder(){for(const id of ['bentoMain','bentoSide1','bentoSide2','bentoTreat']){const e=$(`#${id}`);if(e){const value=e.value;e.innerHTML=recipeOptions(value);if(value)e.value=value}}renderBentoBalance();$('#savedBentos').innerHTML=state.bentos.length?[...state.bentos].reverse().map(b=>{const ids=[b.main,b.side1,b.side2,b.treat].filter(Boolean),rs=ids.map(getRecipe).filter(Boolean);return `<div class="smart-card"><div class="match-card-head"><div><b>🍱 ${esc(b.name||'Saved Bento')}</b><small class="muted">${esc(rs.map(r=>r.title).join(' · ')||'Empty bento')}</small></div></div><div class="action-row" style="margin-top:10px;margin-bottom:0"><button class="soft-btn" data-bento-grocery="${b.id}">Add groceries</button><button class="danger-btn" data-bento-delete="${b.id}">Delete</button></div></div>`}).join(''):emptyCard('Build your first lunchbox combination above.')}
  function renderBentoBalance(){const ids=['bentoMain','bentoSide1','bentoSide2','bentoTreat'].map(id=>$(`#${id}`)?.value).filter(Boolean),rs=ids.map(getRecipe).filter(Boolean),cats=rs.map(r=>(r.category||'').toLowerCase()),tags=[];tags.push(`<span class="balance-dot ${rs.length>=3?'good':''}">${rs.length}/4 compartments</span>`);tags.push(`<span class="balance-dot ${cats.some(c=>/side|salad|soup/.test(c))?'good':''}">🥬 side</span>`);tags.push(`<span class="balance-dot ${cats.some(c=>/dessert|snack/.test(c))?'good':''}">🍓 treat</span>`);tags.push(`<span class="balance-dot ${rs.some(r=>r.freezer==='yes')?'good':''}">❄ pack-ahead</span>`);$('#bentoBalance').innerHTML=tags.join('')}

  function leftoverRemix(l){const s=l.name.toLowerCase();if(/rice/.test(s))return'fried rice, rice balls or soup';if(/chicken/.test(s))return'sandwich, fried rice or noodle bowl';if(/beef|pork/.test(s))return'wrap, rice bowl or noodles';if(/veget/.test(s))return'omelet, soup or pasta';if(/curry/.test(s))return'curry udon or baked rice';return'wrap, rice bowl, soup or lunchbox side'}
  function renderLeftovers(){const list=[...state.leftovers].sort((a,b)=>daysUntil(a.useBy)-daysUntil(b.useBy));const soon=list.filter(l=>{const d=daysUntil(l.useBy);return d>=0&&d<=2}).length,total=list.reduce((n,l)=>n+Number(l.portions||0),0);$('#leftoverSummary').innerHTML=`<div class="stat-card"><strong>${list.length}</strong><small>containers</small></div><div class="stat-card"><strong>${total}</strong><small>portions</small></div><div class="stat-card"><strong>${soon}</strong><small>use soon</small></div>`;$('#leftoversList').innerHTML=list.length?list.map(l=>{const d=daysUntil(l.useBy),status=Number.isFinite(d)?(d<0?'expired':d===0?'use today':`${d}d left`):'no date';return `<div class="smart-card"><div class="match-card-head"><div><b>♻️ ${esc(l.name)}</b><small class="muted">${l.portions} portion${l.portions==1?'':'s'} · ${esc(l.location||'Fridge')} · ${esc(status)}</small></div></div><p class="muted" style="margin-top:7px">Remix: ${esc(leftoverRemix(l))}</p><div class="action-row" style="margin-top:10px;margin-bottom:0"><button class="soft-btn" data-leftover-plan="${l.id}">Plan tomorrow lunch</button><button class="soft-btn" data-leftover-use="${l.id}">Use 1 portion</button><button class="danger-btn" data-leftover-delete="${l.id}">Delete</button></div></div>`}).join(''):emptyCard('No leftovers saved. Planned extras can land here after cooking.','Add leftover','add-leftover')}

  function renderCollections(){const custom=[...new Set(state.recipes.map(r=>r.collection).filter(Boolean))].sort();const cards=[['♡','Favorites',state.recipes.filter(r=>r.favorite).length,'Favorites'],['⚡','Quick Meals',state.recipes.filter(r=>totalTime(r)<=30).length,'Quick'],['🧼','Low Cleanup',state.recipes.filter(r=>Number(r.cleanup||2)<=1).length,'Low Cleanup'],['❄️','Freezer Friendly',state.recipes.filter(r=>r.freezer==='yes').length,'Freezer Friendly'],['🌱','Never Cooked',state.recipes.filter(r=>countCooked(r.id)===0).length,'NeverCooked'],...custom.map(c=>['📚',c,state.recipes.filter(r=>r.collection===c).length,`Collection:${c}`])];$('#collectionsGrid').innerHTML=cards.map(([icon,name,count,filter])=>`<button class="collection-card" data-collection-filter="${esc(filter)}"><span>${icon}</span><b>${esc(name)}</b><small>${count} recipe${count===1?'':'s'}</small></button>`).join('')}

  function renderInsights(){const now=Date.now(),weekAgo=now-7*86400000,monthAgo=now-30*86400000,cookedWeek=state.history.filter(h=>new Date(h.date).getTime()>=weekAgo).length,cookedMonth=state.history.filter(h=>new Date(h.date).getTime()>=monthAgo).length,unique=new Set(state.history.filter(h=>new Date(h.date).getTime()>=monthAgo).map(h=>h.recipeId)).size;$('#insightStats').innerHTML=`<div class="stat-card"><strong>${cookedWeek}</strong><small>cooked this week</small></div><div class="stat-card"><strong>${unique}</strong><small>different recipes</small></div><div class="stat-card"><strong>${state.stats.rescuedCount||0}</strong><small>food rescues</small></div>`;const g=state.goals,cookP=g.cookPerWeek?Math.min(100,Math.round(cookedWeek/g.cookPerWeek*100)):100,newP=g.newPerMonth?Math.min(100,Math.round(unique/g.newPerMonth*100)):100,rescueP=g.rescuePerMonth?Math.min(100,Math.round((state.stats.rescuedCount||0)/g.rescuePerMonth*100)):100;$('#goalCards').innerHTML=[['Home-cooked meals',cookedWeek,g.cookPerWeek,cookP],['Different recipes this month',unique,g.newPerMonth,newP],['Pantry rescues',state.stats.rescuedCount||0,g.rescuePerMonth,rescueP]].map(x=>`<div class="smart-card"><div class="match-card-head"><b>${x[0]}</b><strong>${x[1]}/${x[2]}</strong></div><div class="goal-progress"><i style="width:${x[3]}%"></i></div></div>`).join('');const counts=state.recipes.map(r=>({r,n:countCooked(r.id)})).sort((a,b)=>b.n-a.n),top=counts.filter(x=>x.n>0).slice(0,3),never=counts.filter(x=>x.n===0).slice(0,3);$('#rotationInsights').innerHTML=`<div class="smart-card"><h3>🏆 Regular rotation</h3>${top.length?top.map(x=>`<button class="list-card" data-recipe-id="${x.r.id}"><span class="emoji">${foodEmoji(x.r)}</span><span class="content"><b>${esc(x.r.title)}</b><small>Cooked ${x.n} time${x.n===1?'':'s'}</small></span><span class="meta">›</span></button>`).join(''):'<p class="muted">Cook a few recipes and Bento will learn your regular rotation.</p>'}</div><div class="smart-card"><h3>🌱 Try something new</h3>${never.length?never.map(x=>`<button class="list-card" data-recipe-id="${x.r.id}"><span class="emoji">${foodEmoji(x.r)}</span><span class="content"><b>${esc(x.r.title)}</b><small>Saved but never cooked</small></span><span class="meta">›</span></button>`).join(''):'<p class="muted">You have tried every saved recipe. Nice!</p>'}</div>`}

  function renderHistory(){const list=[...state.history].sort((a,b)=>String(b.date).localeCompare(String(a.date)));$('#historyList').innerHTML=list.length?list.map(h=>{const r=getRecipe(h.recipeId);return `<div class="list-card"><button class="content" ${r?`data-recipe-id="${r.id}"`:''}><b>${foodEmoji(r)} ${esc(r?.title||h.title||'Recipe')}</b><small>${esc(formatDateTime(h.date))}</small></button><button class="meta" data-history-rate="${h.id}" aria-label="Rate">${h.rating?`${'★'.repeat(h.rating)}`:'Rate ☆'}</button></div>`}).join(''):emptyCard('When you finish cooking a recipe, it will be remembered here.')}
  function renderSettings(){applyTheme();$('#displayNameInput').value=state.settings.displayName||'';$('#servingsInput').value=state.settings.defaultServings||2;$('#unitsSelect').value=state.settings.units||'metric';$('#weekStartSelect').value=state.settings.weekStart||'monday';$('#dietInput').value=state.settings.diet||'';$('#allergyInput').value=state.settings.allergies||'';$('#equipmentInput').value=state.settings.equipment||'';$('#weeklyGoalInput').value=state.settings.weeklyGoal||4;$('#themePicker').innerHTML=Object.entries(THEMES).map(([k,t])=>`<button class="theme-swatch ${state.settings.theme===k?'active':''}" data-theme="${k}" style="background:linear-gradient(135deg,${t.soft},${t.accent})"><span>${t.label}</span></button>`).join('')}
  function renderCurrentView(){applyTheme();const map={home:renderHome,plan:renderPlan,recipes:renderRecipes,pantry:renderPantry,grocery:renderGrocery,cookwith:renderCookMatches,smart:renderSmart,bentobox:renderBentoBuilder,leftovers:renderLeftovers,collections:renderCollections,insights:renderInsights,favorites:renderRecipes,history:renderHistory,settings:renderSettings};(map[currentView]||(()=>{}))()}

  function openDialog(d){if(d&&!d.open)d.showModal()}
  function openRecipeForm(r=null){$('#recipeForm').reset();$('#recipeId').value=r?.id||'';$('#recipeDialogTitle').textContent=r?'Edit Recipe':'Add Recipe';$('#recipeTitleInput').value=r?.title||'';$('#recipeCategoryInput').value=r?.category||'Dinner';$('#recipeCuisineInput').value=r?.cuisine||'';$('#recipePrepInput').value=r?.prep??0;$('#recipeCookInput').value=r?.cook??0;$('#recipeServingsInput').value=r?.servings||state.settings.defaultServings||2;$('#recipeEnergyInput').value=r?.energy||'normal';$('#recipeCleanupInput').value=String(r?.cleanup||2);$('#recipeFreezerInput').value=r?.freezer||'no';$('#recipeEquipmentInput').value=r?.equipment||'';$('#recipeIngredientsInput').value=(r?.ingredients||[]).join('\n');$('#recipeStepsInput').value=(r?.steps||[]).join('\n');$('#recipeNotesInput').value=r?.notes||'';$('#recipeCollectionInput').value=r?.collection||'';$('#recipeSourceInput').value=r?.source||'';openDialog($('#recipeDialog'));setTimeout(()=>$('#recipeTitleInput').focus(),80)}
  function openPantryForm(p=null){$('#pantryForm').reset();$('#pantryId').value=p?.id||'';$('#pantryDialogTitle').textContent=p?'Edit Pantry Item':'Add Pantry Item';$('#pantryNameInput').value=p?.name||'';$('#pantryQtyInput').value=p?.quantity??1;$('#pantryUnitInput').value=p?.unit||'';$('#pantryLocationInput').value=p?.location||'Pantry';$('#pantryExpiryInput').value=p?.expiry||'';$('#pantryOpenedInput').value=p?.opened||'';$('#pantryPackageInput').value=p?.packageSize||'';$('#pantryStoreInput').value=p?.store||'';$('#pantryStapleInput').checked=!!p?.staple;$('#pantryLowInput').checked=!!p?.lowStock;openDialog($('#pantryDialog'));setTimeout(()=>$('#pantryNameInput').focus(),80)}
  function openMealForm(date,slot){const cur=state.mealPlan[date]?.[slot];$('#mealDateInput').value=date;$('#mealSlotInput').value=slot;$('#mealDialogDate').textContent=parseDate(date).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});$('#mealDialogTitle').textContent=slot[0].toUpperCase()+slot.slice(1);$('#mealRecipeSelect').innerHTML=recipeOptions(cur?.recipeId||'');$('#mealCustomInput').value=cur?.custom||'';const r=getRecipe(cur?.recipeId);$('#mealServingsInput').value=cur?.servings||r?.servings||state.settings.defaultServings||2;$('#mealPrepNoteInput').value=cur?.prepNote||'';$('#mealLeftoversInput').checked=!!cur?.planLeftovers;$('#removeMealButton').style.visibility=cur?'visible':'hidden';openDialog($('#mealDialog'))}
  function openLeftoverForm(){ $('#leftoverForm').reset();$('#leftoverPortionsInput').value=1;const d=new Date();d.setDate(d.getDate()+3);$('#leftoverUseByInput').value=dateKey(d);openDialog($('#leftoverDialog')) }
  function openRecipeDetail(id){const r=getRecipe(id);if(!r)return;$('#recipeDetailContent').innerHTML=`<div class="sheet-handle"></div><div class="dialog-title"><div><p class="eyebrow">${esc(r.cuisine||'Recipe')}</p><h2>${esc(r.title)}</h2></div><button class="icon-btn close-dialog">×</button></div><div class="detail-hero"><div class="food-emoji">${foodEmoji(r)}</div><div class="detail-meta"><span class="badge">${totalTime(r)} min</span><span class="badge">${r.servings||2} servings</span><span class="badge">${esc(r.category||'Other')}</span><span class="badge">${r.energy} effort</span><span class="badge">cleanup ${r.cleanup}/3</span>${r.freezer==='yes'?'<span class="badge">❄ freezer friendly</span>':''}${r.collection?`<span class="badge">${esc(r.collection)}</span>`:''}</div></div><div class="detail-section"><h3>Ingredients</h3>${(r.ingredients||[]).length?r.ingredients.map(i=>`<div class="ingredient-line">○ ${esc(i)}</div>`).join(''):'<span class="muted">No ingredients added.</span>'}</div><div class="detail-section"><h3>Steps</h3>${(r.steps||[]).length?r.steps.map((s,i)=>`<div class="step-line"><b>${i+1}.</b> ${esc(s)}</div>`).join(''):'<span class="muted">No steps added.</span>'}</div>${r.notes?`<div class="detail-section"><h3>Next-time notes</h3><p>${esc(r.notes)}</p></div>`:''}${r.equipment?`<div class="detail-section"><h3>Equipment</h3><p>${esc(r.equipment)}</p></div>`:''}${r.source?`<div class="detail-section"><h3>Source</h3><p>${esc(r.source)}</p></div>`:''}<div class="detail-actions"><button class="soft-btn" data-detail-fav="${r.id}">${r.favorite?'♥ Favorited':'♡ Favorite'}</button><button class="soft-btn" data-detail-edit="${r.id}">Edit</button><button class="soft-btn" data-detail-grocery="${r.id}">Add ingredients</button><button class="soft-btn" data-detail-plan="${r.id}">Plan this</button><button class="primary-btn" data-start-cook="${r.id}">Start cooking</button><button class="danger-btn" data-detail-delete="${r.id}">Delete recipe</button></div>`;openDialog($('#recipeDetailDialog'))}

  async function requestWakeLock(){try{if('wakeLock'in navigator&&!wakeLock)wakeLock=await navigator.wakeLock.request('screen')}catch{}}
  async function releaseWakeLock(){try{await wakeLock?.release()}catch{}wakeLock=null}
  function formatTimer(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
  function startCooking(id){const r=getRecipe(id);if(!r)return;cookingSession={recipeId:id,step:0,checked:new Set()};timerSeconds=0;stopCookingTimer(false);requestWakeLock();renderCookingMode()}
  function renderCookingMode(){const r=getRecipe(cookingSession?.recipeId);if(!r)return;const steps=(r.steps||[]).length?r.steps:['Enjoy making your recipe!'],i=clamp(cookingSession.step,0,steps.length-1);cookingSession.step=i;$('#recipeDetailContent').innerHTML=`<div class="cook-mode"><div class="sheet-handle"></div><div class="dialog-title"><div><p class="eyebrow">Cooking mode · ${i+1}/${steps.length}</p><h2>${esc(r.title)}</h2></div><button class="icon-btn close-dialog">×</button></div><div class="cook-progress"><i style="width:${((i+1)/steps.length)*100}%"></i></div><div class="cook-step">${esc(steps[i])}</div><div class="cook-ingredients">${(r.ingredients||[]).slice(0,16).map((ing,idx)=>`<label class="cook-ingredient"><input type="checkbox" data-cook-ing="${idx}" ${cookingSession.checked.has(idx)?'checked':''}><span>${esc(ing)}</span></label>`).join('')}</div><div class="timer-box"><strong id="timerDisplay">${formatTimer(timerSeconds)}</strong><div class="action-row" style="justify-content:center;margin-top:8px"><button class="soft-btn" data-timer-add="60">+1 min</button><button class="soft-btn" data-timer-add="300">+5 min</button><button class="soft-btn" data-timer-toggle>${cookingTimer?'Pause':'Start timer'}</button><button class="soft-btn" data-timer-reset>Reset</button></div></div><div class="detail-actions"><button class="soft-btn" data-cook-prev ${i===0?'disabled':''}>‹ Previous</button><button class="soft-btn" data-cook-next>${i===steps.length-1?'Stay here':'Next ›'}</button><button class="primary-btn" data-cook-finish>Finish cooking</button></div></div>`}
  function startCookingTimer(){if(cookingTimer)return;if(timerSeconds<=0)timerSeconds=60;cookingTimer=setInterval(()=>{timerSeconds=Math.max(0,timerSeconds-1);const d=$('#timerDisplay');if(d)d.textContent=formatTimer(timerSeconds);if(timerSeconds===0){stopCookingTimer(false);toast('Timer finished ✿');navigator.vibrate?.([120,80,120]);renderCookingMode()}},1000);renderCookingMode()}
  function stopCookingTimer(render=true){if(cookingTimer){clearInterval(cookingTimer);cookingTimer=null}if(render&&cookingSession)renderCookingMode()}
  function finishCooking(){const r=getRecipe(cookingSession?.recipeId);if(!r)return;state.history.push({id:uid('history'),recipeId:r.id,title:r.title,date:new Date().toISOString(),rating:0});const today=state.mealPlan[dateKey(new Date())]||{},planned=Object.values(today).find(i=>i?.recipeId===r.id&&i.planLeftovers);if(planned){const d=new Date();d.setDate(d.getDate()+3);state.leftovers.push({id:uid('left'),name:r.title,portions:1,useBy:dateKey(d),location:'Fridge',notes:'Planned extra portion',createdAt:new Date().toISOString()})}const expiring=expiringIngredientNames();if((r.ingredients||[]).some(i=>expiring.some(p=>ingredientMatches(i,p))))state.stats.rescuedCount=(state.stats.rescuedCount||0)+1;commit();cookingSession=null;stopCookingTimer(false);releaseWakeLock();$('#recipeDetailDialog').close();toast(planned?'Cooked — leftover portion saved ♡':'Saved to cooking history ♡');if(currentView==='history')renderHistory()}

  function addRecipeIngredientsToGrocery(r,missingOnly=false){const pantry=state.pantry.map(p=>p.name);let lines=r.ingredients||[];if(missingOnly)lines=lines.filter(i=>!pantry.some(p=>ingredientMatches(i,p)));let added=0;for(const line of lines){const name=ingredientName(line)||line.trim();if(!name)continue;const ex=state.grocery.find(g=>ingredientMatches(g.text,name)&&!g.checked);if(!ex){state.grocery.push({id:uid('g'),text:line.trim(),checked:false,category:groceryCategory(line),source:`recipe:${r.id}`});added++}}commit();toast(added?`${added} item${added===1?'':'s'} added to groceries`:'Everything is already listed')}
  function generateGroceriesFromWeek(){const recipes=[];weekDates().forEach(d=>{const p=state.mealPlan[dateKey(d)]||{};MEAL_SLOTS.forEach(slot=>{const r=getRecipe(p[slot]?.recipeId);if(r)recipes.push(r)})});if(!recipes.length){toast('Plan at least one saved recipe this week first');return}const pantry=state.pantry.map(p=>p.name);let added=0;for(const r of recipes)for(const line of r.ingredients||[]){const name=ingredientName(line)||line.trim();if(!name||pantry.some(p=>ingredientMatches(p,name)))continue;const ex=state.grocery.find(g=>ingredientMatches(g.text,name)&&!g.checked);if(!ex){state.grocery.push({id:uid('g'),text:line.trim(),checked:false,category:groceryCategory(line),source:'week-plan'});added++}}commit();toast(added?`${added} grocery item${added===1?'':'s'} added`:'Your current pantry/list already covers the plan')}
  function lowStockToGrocery(){let n=0;for(const p of state.pantry.filter(x=>x.lowStock)){if(!state.grocery.some(g=>!g.checked&&ingredientMatches(g.text,p.name))){state.grocery.push({id:uid('g'),text:p.name,checked:false,category:groceryCategory(p.name),source:'low-stock'});n++}}commit();toast(n?`${n} low-stock item${n===1?'':'s'} added`:'Low-stock items are already listed')}
  function checkedToPantry(){const checked=state.grocery.filter(g=>g.checked);if(!checked.length){toast('Check purchased items first');return}for(const g of checked){const name=ingredientName(g.text)||g.text;const existing=state.pantry.find(p=>ingredientMatches(p.name,name));if(existing){existing.quantity=Number(existing.quantity||0)+1;existing.lowStock=false;existing.updatedAt=new Date().toISOString()}else state.pantry.push({id:uid('pantry'),name:name[0]?.toUpperCase()+name.slice(1),quantity:1,unit:'',location:'Pantry',expiry:'',opened:'',packageSize:'',store:'',staple:false,lowStock:false,updatedAt:new Date().toISOString()})}state.grocery=state.grocery.filter(g=>!g.checked);commit();toast(`${checked.length} purchased item${checked.length===1?'':'s'} moved to pantry`)}
  async function shareGroceries(){const items=state.grocery.filter(g=>!g.checked);if(!items.length){toast('Nothing unchecked to share');return}const text=['Bento Grocery List',...items.map(g=>`☐ ${g.text}`)].join('\n');try{if(navigator.share)await navigator.share({title:'Bento Grocery List',text});else{await navigator.clipboard.writeText(text);toast('Grocery list copied')}}catch{}}

  function exportBackup(){persistNow();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bento-backup-${dateKey(new Date())}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Backup exported')}
  async function importBackup(file){if(!file)return;try{const raw=JSON.parse(await file.text());state=normalizeState(raw);persistNow();renderCurrentView();renderGlobalBadges();toast('Backup restored')}catch{toast('That backup could not be read')}}

  function copyWeek(){const from=weekDates(),to=weekDates(weekOffset+1);let count=0;from.forEach((d,i)=>{const src=state.mealPlan[dateKey(d)];if(src){state.mealPlan[dateKey(to[i])]=JSON.parse(JSON.stringify(src));count+=Object.keys(src).length}});commit();toast(count?`Copied ${count} meal${count===1?'':'s'} to next week`:'Nothing planned to copy')}
  function clearWeek(){if(!confirm('Clear all meals from this visible week?'))return;weekDates().forEach(d=>delete state.mealPlan[dateKey(d)]);commit();toast('Week cleared')}

  function renderCompleteMeal(){const id=$('#completeRecipeSelect')?.value,r=getRecipe(id),out=$('#completeMealOutput');if(!r||!out)return;const sideCats=['Side','Soup','Snack','Dessert'];const picks=state.recipes.filter(x=>x.id!==r.id&&sideCats.includes(x.category)).sort((a,b)=>totalTime(a)-totalTime(b)).slice(0,4);out.innerHTML=`<div class="detail-section"><h3>${foodEmoji(r)} ${esc(r.title)}</h3>${picks.length?`<p class="muted">Pair it with:</p>${picks.map(x=>`<button class="list-card" data-recipe-id="${x.id}"><span class="emoji">${foodEmoji(x)}</span><span class="content"><b>${esc(x.title)}</b><small>${esc(x.category)} · ${totalTime(x)} min</small></span><span class="meta">›</span></button>`).join('')}`:'<p class="muted">Save some Side, Soup, Snack or Dessert recipes and Bento can complete the meal.</p>'}</div>`}
  function renderDeadline(){const r=getRecipe($('#deadlineRecipeSelect')?.value),time=$('#deadlineTime')?.value,out=$('#deadlineOutput');if(!r||!time||!out)return;const [hh,mm]=time.split(':').map(Number),deadline=new Date();deadline.setHours(hh,mm,0,0);const prep=Number(r.prep||0),cook=Number(r.cook||0),start=new Date(deadline.getTime()-(prep+cook)*60000),cookStart=new Date(deadline.getTime()-cook*60000),fmt=d=>d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});out.innerHTML=`<div class="detail-section"><h3>Ready by ${fmt(deadline)}</h3><div class="timeline"><div class="timeline-row"><time>${fmt(start)}</time><div><b>Start prep</b><small class="muted">Give yourself ${prep} min for prep.</small></div></div><div class="timeline-row"><time>${fmt(cookStart)}</time><div><b>Start cooking</b><small class="muted">Cook for about ${cook} min.</small></div></div><div class="timeline-row"><time>${fmt(deadline)}</time><div><b>Serve ✿</b><small class="muted">${esc(r.title)} should be ready.</small></div></div></div></div>`}
  function renderThreeMatch(){const vals=($('#threeIngredientsInput')?.value||'').split(',').map(s=>s.trim()).filter(Boolean).slice(0,3),out=$('#threeOutput');if(!out)return;if(!vals.length){out.innerHTML='<p class="muted" style="margin-top:10px">Add at least one ingredient.</p>';return}const scored=state.recipes.map(r=>({r,n:vals.filter(v=>(r.ingredients||[]).some(i=>ingredientMatches(i,v))).length})).filter(x=>x.n>0).sort((a,b)=>b.n-a.n||totalTime(a.r)-totalTime(b.r));out.innerHTML=scored.length?scored.slice(0,8).map(x=>`<button class="list-card" data-recipe-id="${x.r.id}"><span class="emoji">${foodEmoji(x.r)}</span><span class="content"><b>${esc(x.r.title)}</b><small>Uses ${x.n}/${vals.length} chosen ingredients</small></span><span class="meta">›</span></button>`).join(''):'<p class="muted" style="margin-top:10px">No saved recipes use those ingredients yet.</p>'}

  document.addEventListener('click',e=>{
    const nav=e.target.closest('[data-nav]');if(nav){navigate(nav.dataset.nav);return}
    const link=e.target.closest('[data-view-link]');if(link){if(link.dataset.autoTool)activeSmartTool=link.dataset.autoTool;navigate(link.dataset.viewLink);return}
    if(e.target.closest('[data-back]')){back();return}
    if(e.target.closest('.close-dialog')){e.target.closest('dialog')?.close();return}
    const action=e.target.closest('[data-action]');if(action){const a=action.dataset.action;if(a==='add-recipe')openRecipeForm();if(a==='add-pantry')openPantryForm();if(a==='add-grocery'){navigate('grocery');setTimeout(()=>$('#groceryAddInput')?.focus(),80)}if(a==='add-leftover')openLeftoverForm();action.closest('dialog')?.close();return}
    const rid=e.target.closest('[data-recipe-id]');if(rid){openRecipeDetail(rid.dataset.recipeId);return}
    const fav=e.target.closest('[data-favorite]');if(fav){const r=getRecipe(fav.dataset.favorite);if(r){r.favorite=!r.favorite;commit();toast(r.favorite?'Added to favorites':'Removed from favorites')}return}
    const p=e.target.closest('[data-pantry-id]');if(p){openPantryForm(state.pantry.find(x=>x.id===p.dataset.pantryId));return}
    const meal=e.target.closest('[data-meal-date][data-meal-slot]');if(meal){openMealForm(meal.dataset.mealDate,meal.dataset.mealSlot);return}
    const gf=e.target.closest('[data-grocery-delete]');if(gf){state.grocery=state.grocery.filter(g=>g.id!==gf.dataset.groceryDelete);commit();return}
    const miss=e.target.closest('[data-add-missing]');if(miss){const r=getRecipe(miss.dataset.addMissing);if(r)addRecipeIngredientsToGrocery(r,true);return}
    const rf=e.target.closest('[data-recipe-filter]');if(rf){recipeFilter=rf.dataset.recipeFilter;renderRecipes();return}
    const pf=e.target.closest('[data-pantry-filter]');if(pf){pantryFilter=pf.dataset.pantryFilter;renderPantry();return}
    const mf=e.target.closest('[data-match-filter]');if(mf){matchFilter=mf.dataset.matchFilter;$$('[data-match-filter]').forEach(x=>x.classList.toggle('active',x===mf));renderCookMatches();return}
    const th=e.target.closest('[data-theme]');if(th){state.settings.theme=th.dataset.theme;commit();renderSettings();return}
    const st=e.target.closest('[data-smart-tool]');if(st){activeSmartTool=st.dataset.smartTool;renderSmart();return}
    if(e.target.closest('[data-smart-reroll]')){renderSmart();return}
    if(e.target.closest('[data-complete-meal]')){renderCompleteMeal();return}
    if(e.target.closest('[data-deadline-build]')){renderDeadline();return}
    if(e.target.closest('[data-three-match]')){renderThreeMatch();return}
    const cf=e.target.closest('[data-collection-filter]');if(cf){const f=cf.dataset.collectionFilter;if(f==='NeverCooked'){recipeFilter='All';navigate('recipes');$('#recipeSearch').value='';const never=state.recipes.filter(r=>countCooked(r.id)===0);$('#recipeGrid').innerHTML=never.length?never.map(recipeCard).join(''):emptyCard('Every saved recipe has been cooked.');}else{recipeFilter=f;navigate('recipes')}return}
    const bg=e.target.closest('[data-bento-grocery]');if(bg){const b=state.bentos.find(x=>x.id===bg.dataset.bentoGrocery);if(b){[b.main,b.side1,b.side2,b.treat].filter(Boolean).map(getRecipe).filter(Boolean).forEach(r=>addRecipeIngredientsToGrocery(r,false));navigate('grocery')}return}
    const bd=e.target.closest('[data-bento-delete]');if(bd){state.bentos=state.bentos.filter(x=>x.id!==bd.dataset.bentoDelete);commit();return}
    const lp=e.target.closest('[data-leftover-plan]');if(lp){const l=state.leftovers.find(x=>x.id===lp.dataset.leftoverPlan);if(l){const d=new Date();d.setDate(d.getDate()+1);const k=dateKey(d);state.mealPlan[k]||={};state.mealPlan[k].lunch={custom:`Leftover: ${l.name}`,servings:Math.min(1,Number(l.portions||1)),prepNote:'Use saved leftovers'};commit();toast('Planned for tomorrow lunch')}return}
    const lu=e.target.closest('[data-leftover-use]');if(lu){const l=state.leftovers.find(x=>x.id===lu.dataset.leftoverUse);if(l){l.portions=Math.max(0,Number(l.portions||1)-1);if(l.portions<=0)state.leftovers=state.leftovers.filter(x=>x.id!==l.id);state.stats.rescuedCount=(state.stats.rescuedCount||0)+1;commit();toast('Leftover used ♻️')}return}
    const ld=e.target.closest('[data-leftover-delete]');if(ld){state.leftovers=state.leftovers.filter(x=>x.id!==ld.dataset.leftoverDelete);commit();return}
    const hr=e.target.closest('[data-history-rate]');if(hr){const h=state.history.find(x=>x.id===hr.dataset.historyRate);if(h){h.rating=(Number(h.rating)||0)%5+1;commit()}return}
    const df=e.target.closest('[data-detail-fav]');if(df){const r=getRecipe(df.dataset.detailFav);if(r){r.favorite=!r.favorite;commit(false);openRecipeDetail(r.id)}return}
    const de=e.target.closest('[data-detail-edit]');if(de){const r=getRecipe(de.dataset.detailEdit);$('#recipeDetailDialog').close();openRecipeForm(r);return}
    const dg=e.target.closest('[data-detail-grocery]');if(dg){const r=getRecipe(dg.dataset.detailGrocery);if(r)addRecipeIngredientsToGrocery(r,false);return}
    const dp=e.target.closest('[data-detail-plan]');if(dp){$('#recipeDetailDialog').close();navigate('plan');toast('Tap a meal slot to add this recipe');return}
    const dd=e.target.closest('[data-detail-delete]');if(dd&&confirm('Delete this recipe?')){const id=dd.dataset.detailDelete;state.recipes=state.recipes.filter(r=>r.id!==id);Object.values(state.mealPlan).forEach(day=>MEAL_SLOTS.forEach(slot=>{if(day?.[slot]?.recipeId===id)delete day[slot]}));commit(false);$('#recipeDetailDialog').close();renderCurrentView();toast('Recipe deleted');return}
    const sc=e.target.closest('[data-start-cook]');if(sc){startCooking(sc.dataset.startCook);return}
    if(e.target.closest('[data-cook-prev]')){cookingSession.step--;renderCookingMode();return}
    if(e.target.closest('[data-cook-next]')){const r=getRecipe(cookingSession.recipeId);cookingSession.step=Math.min(Math.max(0,(r.steps||[]).length-1),cookingSession.step+1);renderCookingMode();return}
    if(e.target.closest('[data-cook-finish]')){finishCooking();return}
    const ta=e.target.closest('[data-timer-add]');if(ta){timerSeconds+=Number(ta.dataset.timerAdd);renderCookingMode();return}
    if(e.target.closest('[data-timer-toggle]')){cookingTimer?stopCookingTimer():startCookingTimer();return}
    if(e.target.closest('[data-timer-reset]')){timerSeconds=0;stopCookingTimer();return}
  });

  document.addEventListener('change',e=>{
    const g=e.target.closest('[data-grocery-check]');if(g){const item=state.grocery.find(x=>x.id===g.dataset.groceryCheck);if(item){item.checked=g.checked;queuePersist();renderGrocery();renderGlobalBadges()}return}
    const ci=e.target.closest('[data-cook-ing]');if(ci&&cookingSession){const i=Number(ci.dataset.cookIng);ci.checked?cookingSession.checked.add(i):cookingSession.checked.delete(i);return}
    if(['bentoMain','bentoSide1','bentoSide2','bentoTreat'].includes(e.target.id)){renderBentoBalance();return}
    if(['smartTime','smartEnergy','smartEquipment'].includes(e.target.id)){renderSmart();return}
  });

  $('#recipeForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#recipeId').value,ex=id?getRecipe(id):null,r={id:id||uid('recipe'),title:$('#recipeTitleInput').value.trim(),category:$('#recipeCategoryInput').value,cuisine:$('#recipeCuisineInput').value.trim(),prep:Number($('#recipePrepInput').value)||0,cook:Number($('#recipeCookInput').value)||0,servings:Number($('#recipeServingsInput').value)||2,energy:$('#recipeEnergyInput').value,cleanup:Number($('#recipeCleanupInput').value)||2,freezer:$('#recipeFreezerInput').value,equipment:$('#recipeEquipmentInput').value.trim(),ingredients:$('#recipeIngredientsInput').value.split('\n').map(s=>s.trim()).filter(Boolean),steps:$('#recipeStepsInput').value.split('\n').map(s=>s.trim()).filter(Boolean),notes:$('#recipeNotesInput').value.trim(),collection:$('#recipeCollectionInput').value.trim(),source:$('#recipeSourceInput').value.trim(),favorite:ex?.favorite||false,createdAt:ex?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!r.title){toast('Give the recipe a name');return}ex?Object.assign(ex,r):state.recipes.push(r);commit(false);$('#recipeDialog').close();navigate('recipes');toast(ex?'Recipe updated':'Recipe saved')});
  $('#pantryForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#pantryId').value,ex=state.pantry.find(p=>p.id===id),p={id:id||uid('pantry'),name:$('#pantryNameInput').value.trim(),quantity:Number($('#pantryQtyInput').value)||0,unit:$('#pantryUnitInput').value.trim(),location:$('#pantryLocationInput').value,expiry:$('#pantryExpiryInput').value,opened:$('#pantryOpenedInput').value,packageSize:$('#pantryPackageInput').value.trim(),store:$('#pantryStoreInput').value.trim(),staple:$('#pantryStapleInput').checked,lowStock:$('#pantryLowInput').checked,updatedAt:new Date().toISOString()};if(!p.name){toast('Add an item name');return}ex?Object.assign(ex,p):state.pantry.push(p);commit(false);$('#pantryDialog').close();if(currentView==='pantry')renderPantry();renderGlobalBadges();toast(ex?'Pantry item updated':'Added to pantry')});
  $('#mealForm').addEventListener('submit',e=>{e.preventDefault();const date=$('#mealDateInput').value,slot=$('#mealSlotInput').value,recipeId=$('#mealRecipeSelect').value,custom=$('#mealCustomInput').value.trim(),servings=clamp(Number($('#mealServingsInput').value)||state.settings.defaultServings||2,1,30),prepNote=$('#mealPrepNoteInput').value.trim(),planLeftovers=$('#mealLeftoversInput').checked;state.mealPlan[date]||={};if(recipeId)state.mealPlan[date][slot]={recipeId,servings,prepNote,planLeftovers};else if(custom)state.mealPlan[date][slot]={custom,servings,prepNote,planLeftovers};else delete state.mealPlan[date][slot];commit();$('#mealDialog').close();toast('Meal plan updated')});
  $('#leftoverForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#leftoverNameInput').value.trim();if(!name)return;state.leftovers.push({id:uid('left'),name,portions:Number($('#leftoverPortionsInput').value)||1,useBy:$('#leftoverUseByInput').value,location:$('#leftoverLocationInput').value,notes:$('#leftoverNotesInput').value.trim(),createdAt:new Date().toISOString()});commit(false);$('#leftoverDialog').close();navigate('leftovers');toast('Leftover saved ♻️')});
  $('#goalForm').addEventListener('submit',e=>{e.preventDefault();state.goals.cookPerWeek=Number($('#goalCookInput').value)||0;state.goals.newPerMonth=Number($('#goalNewInput').value)||0;state.goals.rescuePerMonth=Number($('#goalRescueInput').value)||0;commit();$('#goalDialog').close();toast('Goals updated')});

  $('#removeMealButton').addEventListener('click',()=>{const date=$('#mealDateInput').value,slot=$('#mealSlotInput').value;if(state.mealPlan[date])delete state.mealPlan[date][slot];commit();$('#mealDialog').close();toast('Meal removed')});
  $('#mealRecipeSelect').addEventListener('change',()=>{if($('#mealRecipeSelect').value){$('#mealCustomInput').value='';const r=getRecipe($('#mealRecipeSelect').value);if(r)$('#mealServingsInput').value=r.servings||state.settings.defaultServings||2}});$('#mealCustomInput').addEventListener('input',()=>{if($('#mealCustomInput').value.trim())$('#mealRecipeSelect').value=''})
  $('#prevWeek').addEventListener('click',()=>{weekOffset--;renderPlan()});$('#nextWeek').addEventListener('click',()=>{weekOffset++;renderPlan()});$('#copyWeekButton').addEventListener('click',copyWeek);$('#clearWeekButton').addEventListener('click',clearWeek);
  $('#generateGroceriesButton').addEventListener('click',()=>{generateGroceriesFromWeek();navigate('grocery')});$('#groceryFromPlanButton').addEventListener('click',generateGroceriesFromWeek);$('#addLowStockToGrocery').addEventListener('click',lowStockToGrocery);$('#checkedToPantryButton').addEventListener('click',checkedToPantry);
  $('#groceryAddButton').addEventListener('click',()=>{const input=$('#groceryAddInput'),text=input.value.trim();if(!text)return;state.grocery.push({id:uid('g'),text,checked:false,category:groceryCategory(text),source:'manual'});input.value='';commit()});$('#groceryAddInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#groceryAddButton').click()}});$('#clearCheckedButton').addEventListener('click',()=>{state.grocery=state.grocery.filter(g=>!g.checked);commit();toast('Checked items cleared')});$('#shareGroceryButton').addEventListener('click',shareGroceries);$('#shoppingModeButton').addEventListener('click',async()=>{document.body.classList.toggle('shopping-mode');if(document.body.classList.contains('shopping-mode')){await requestWakeLock();toast('Shopping mode on')}else await releaseWakeLock()});
  $('#matchRecipesButton').addEventListener('click',renderCookMatches);$('#customCookIngredients').addEventListener('input',debounce(renderCookMatches,90));$('#pantrySortButton').addEventListener('click',()=>{pantrySort=pantrySort==='expiry'?'name':'expiry';renderPantry()});$('#recipeSearch').addEventListener('input',debounce(renderRecipes,80));$('#recipeSort').addEventListener('change',renderRecipes);$('#pantrySearch').addEventListener('input',debounce(renderPantry,80));
  $('#newBentoButton').addEventListener('click',()=>{$('#bentoNameInput').value='';for(const id of ['bentoMain','bentoSide1','bentoSide2','bentoTreat'])$(`#${id}`).value='';renderBentoBalance()});$('#saveBentoButton').addEventListener('click',()=>{const b={id:uid('bento'),name:$('#bentoNameInput').value.trim()||'My Bento',main:$('#bentoMain').value,side1:$('#bentoSide1').value,side2:$('#bentoSide2').value,treat:$('#bentoTreat').value,createdAt:new Date().toISOString()};if(![b.main,b.side1,b.side2,b.treat].some(Boolean)){toast('Add at least one recipe to the bento');return}state.bentos.push(b);commit();toast('Bento combination saved 🍱')});
  $('#editGoalsButton').addEventListener('click',()=>{$('#goalCookInput').value=state.goals.cookPerWeek;$('#goalNewInput').value=state.goals.newPerMonth;$('#goalRescueInput').value=state.goals.rescuePerMonth;openDialog($('#goalDialog'))});

  for(const [id,key,parser] of [['displayNameInput','displayName',v=>v.trim()],['servingsInput','defaultServings',v=>clamp(Number(v)||2,1,30)],['unitsSelect','units',v=>v],['weekStartSelect','weekStart',v=>v],['dietInput','diet',v=>v.trim()],['allergyInput','allergies',v=>v.trim()],['equipmentInput','equipment',v=>v.trim()],['weeklyGoalInput','weeklyGoal',v=>clamp(Number(v)||0,0,28)]]){$(`#${id}`).addEventListener('change',e=>{state.settings[key]=parser(e.target.value);if(key==='weeklyGoal')state.goals.cookPerWeek=state.settings.weeklyGoal;commit(key==='theme')})}
  $('#exportButton').addEventListener('click',exportBackup);$('#importInput').addEventListener('change',e=>importBackup(e.target.files?.[0]));$('#resetButton').addEventListener('click',()=>{if(confirm('Reset Bento and permanently clear all local recipes, plans, pantry items, groceries, leftovers, history and settings on this device?')){state=defaultState();persistNow();navigate('home');toast('Bento reset')}});
  $('#quickAddButton').addEventListener('click',()=>openDialog($('#quickAddDialog')));$('#brandButton').addEventListener('click',()=>navigate('about'));$('#searchButton').addEventListener('click',()=>{navigate('recipes');setTimeout(()=>$('#recipeSearch').focus(),80)});

  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installButton').classList.remove('hidden')});$('#installButton').addEventListener('click',async()=>{if(!deferredInstallPrompt){toast('On iPhone: Share → Add to Home Screen');return}deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installButton').classList.add('hidden')});window.addEventListener('appinstalled',()=>toast('Bento installed ♡'));if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.matchMedia('(display-mode: standalone)').matches)$('#installButton').classList.remove('hidden');

  ['gesturestart','gesturechange','gestureend'].forEach(type=>document.addEventListener(type,e=>e.preventDefault(),{passive:false}));document.addEventListener('touchstart',e=>{if(e.touches?.length>1)e.preventDefault()},{passive:false});let lastTouchEnd=0;document.addEventListener('touchend',e=>{const now=Date.now();if(now-lastTouchEnd<=300&&!e.target.closest('input,textarea,select'))e.preventDefault();lastTouchEnd=now},{passive:false});document.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('contextmenu',e=>{if(!e.target.closest('input,textarea'))e.preventDefault()});
  $$('dialog').forEach(d=>d.addEventListener('close',()=>{if(d.id==='recipeDetailDialog'){cookingSession=null;stopCookingTimer(false);releaseWakeLock()}}));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')persistNow();else if(cookingSession||document.body.classList.contains('shopping-mode'))requestWakeLock()});window.addEventListener('pagehide',persistNow);
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));

  const hash=location.hash.replace('#','');if(hash&&document.querySelector(`.view[data-view="${hash}"]`))currentView=hash;applyTheme();navigate(currentView,false);
})();
