(()=>{'use strict';
const FLAGS={Japanese:'🇯🇵',Filipino:'🇵🇭',Korean:'🇰🇷',Chinese:'🇨🇳',Thai:'🇹🇭',Vietnamese:'🇻🇳',Indian:'🇮🇳',Italian:'🇮🇹',French:'🇫🇷',Spanish:'🇪🇸',Greek:'🇬🇷',Turkish:'🇹🇷',Mexican:'🇲🇽',American:'🇺🇸',Brazilian:'🇧🇷',Peruvian:'🇵🇪',Moroccan:'🇲🇦',British:'🇬🇧'};
const panel=document.getElementById('recipeBrowsePanel'),grid=document.getElementById('recipeGrid'),filters=document.getElementById('recipeFilters'),resultsTitle=document.getElementById('recipeResultsTitle'),resultsCount=document.getElementById('recipeResultsCount'),cuisineTab=document.querySelector('[data-recipe-browse="cuisines"]'),animeTab=document.querySelector('[data-recipe-browse="anime"]'),search=document.getElementById('recipeSearch'),sort=document.getElementById('recipeSort'),detail=document.getElementById('recipeDetailContent');
if(!panel||!grid)return;
const norm=v=>String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const animeRows=()=>Array.isArray(window.BENTO_RECIPE_LIBRARY)?window.BENTO_RECIPE_LIBRARY.filter(r=>r&&(r.animeDish||r.animeSeries)):[];
const aliases=['jujutsu kaisen','jjk','food wars','shokugeki','campfire cooking','dungeon meshi','delicious in dungeon','emiya','sweetness lightning','restaurant to another world','isekai izakaya','dr stone','laid back camp','yuru camp'];
let animeLimit=30,renderingAnime=false,photoBusy=0;const photoQueue=[],photoCache=new Map();
function queryIsAnime(v){const q=norm(v);if(!q)return false;if(aliases.some(a=>q.includes(a)))return true;return animeRows().some(r=>{const s=norm(r.animeSeries);return s&&(q===s||(q.length>=8&&(q.includes(s)||s.includes(q))))})}
function favoriteIds(){try{const s=JSON.parse(localStorage.getItem('bento.app.state.v1')||'{}');return new Set((s.libraryFavorites||[]).map(String))}catch{return new Set()}}
function animeText(r){return norm([r.title,r.animeSeries,r.animeEpisode,r.animeEpisodeTitle,r.animeDishName,r.realWorldDish,r.adaptationType,r.category,...(r.ingredients||[])].join(' '))}
function animeList(){let list=animeRows().slice(),q=norm(search?.value||'');if(q)list=list.filter(r=>animeText(r).includes(q));const mode=sort?.value||'newest',favs=favoriteIds();if(mode==='name')list.sort((a,b)=>String(a.title).localeCompare(String(b.title)));else if(mode==='quick')list.sort((a,b)=>(+a.total||999)-(+b.total||999)||String(a.title).localeCompare(String(b.title)));else if(mode==='favorite')list.sort((a,b)=>(favs.has(String(b.id))?1:0)-(favs.has(String(a.id))?1:0)||String(a.title).localeCompare(String(b.title)));else list.sort((a,b)=>String(a.id).localeCompare(String(b.id),undefined,{numeric:true}));return list}
function enhanceCuisines(){if(!cuisineTab?.classList.contains('active')||panel.querySelector('.cuisine-picker-card'))return;const source=panel.querySelector('.browse-card-grid'),buttons=source?[...source.querySelectorAll('[data-browse-cuisine]')]:[];if(!source||!buttons.length)return;const selectedButton=buttons.find(b=>b.classList.contains('selected')),selected=selectedButton?.dataset.browseCuisine||'All';source.hidden=true;const picker=document.createElement('div');picker.className='cuisine-picker-card';const summary=selectedButton?.querySelector('small')?.textContent||`${buttons.length} cuisines in Bento`;picker.innerHTML=`<div class="cuisine-picker-head"><span class="cuisine-picker-icon">${selected==='All'?'🌏':(FLAGS[selected]||'🍽️')}</span><span><b>${esc(selected==='All'?'Choose a cuisine':selected)}</b><small>${esc(summary)}</small></span></div><label class="cuisine-select-wrap"><span class="sr-only">Choose cuisine</span><select class="cuisine-browse-select" aria-label="Choose cuisine"><option value="All">🌏 All cuisines</option>${buttons.map(b=>{const c=b.dataset.browseCuisine||'';return `<option value="${esc(c)}" ${c===selected?'selected':''}>${FLAGS[c]||'🍽️'} ${esc(c)}</option>`}).join('')}</select><span aria-hidden="true">⌄</span></label><p class="cuisine-picker-note">${selected==='All'?'Pick a cuisine to narrow the library. This list stays compact as Bento grows.':`Showing ${esc(selected)} recipes only.`}</p>`;picker.querySelector('select')?.addEventListener('change',e=>{const value=e.target.value;if(value==='All'){cuisineTab.click();return}buttons.find(b=>b.dataset.browseCuisine===value)?.click()});panel.insertBefore(picker,source)}
function animeIntro(total){panel.innerHTML=`<div class="anime-library-intro"><span class="anime-library-icon">📺</span><div><b>Anime recipes</b><small>${total} recipes · search by dish or anime title</small><p>All anime recipes live together here. The series stays quiet on cards and appears inside recipe details and references.</p></div></div>`}
function animeCard(r){return `<article class="recipe-card anime-external-card"><button class="recipe-open" data-recipe-id="${esc(r.id)}"><div class="thumb anime-card-thumb"><span class="anime-card-fallback">🍱</span><img class="thumb-img anime-card-photo" data-anime-photo data-anime-id="${esc(r.id)}" alt="${esc(r.realWorldDish||r.title)}" loading="lazy" decoding="async"></div><div class="body"><div class="recipe-card-title"><b>${esc(r.title)}</b></div><small class="recipe-card-meta">${Number(r.total||0)} min · ${esc(r.difficulty||'Easy')} · ${Number(r.servings||2)} servings</small><div class="badge-row recipe-card-badges"><span class="badge">${esc(r.category||'Other')}</span></div></div></button></article>`}
function renderAnime(){if(!animeTab?.classList.contains('active')){if(filters)filters.style.display='';return}renderingAnime=true;try{const all=animeRows(),list=animeList(),visible=list.slice(0,animeLimit);animeIntro(all.length);if(filters)filters.style.display='none';if(resultsTitle)resultsTitle.textContent=(search?.value||'').trim()?'Anime search':'Anime recipes';if(resultsCount)resultsCount.textContent=`${list.length} ${list.length===1?'recipe':'recipes'}`;grid.innerHTML=visible.length?visible.map(animeCard).join('')+(list.length>visible.length?`<div class="load-more-wrap anime-load-more-wrap"><button class="soft-btn load-more-btn" data-anime-more>Show more · ${list.length-visible.length} remaining</button></div>`:''):`<div class="empty-card anime-empty">No Anime recipes match that search.</div>`;observeAnimePhotos()}finally{renderingAnime=false}}
function photoSearchQuery(r){return String((r.photoQueries||[])[0]||r.realWorldDish||r.title||'food').trim()}
async function resolvePhoto(r){const key=String(r.id);if(photoCache.has(key))return photoCache.get(key);const q=photoSearchQuery(r),url='https://commons.wikimedia.org/w/api.php?'+new URLSearchParams({action:'query',generator:'search',gsrsearch:q+' food',gsrnamespace:'6',gsrlimit:'8',prop:'imageinfo',iiprop:'url|mime',iiurlwidth:'640',format:'json',origin:'*'});try{const res=await fetch(url),data=await res.json(),pages=Object.values(data?.query?.pages||{});const bad=/raw|uncooked|ingredient|package|logo|icon|diagram|map|flag|menu|sign|poster|drawing|illustration|anime|manga|toy|plush/i;const page=pages.filter(p=>!bad.test(p.title||'')&&/^image\/(?:jpeg|png|webp)/.test(p.imageinfo?.[0]?.mime||'')).sort((a,b)=>{const at=norm(a.title),bt=norm(b.title),tokens=norm(q).split(' ');return tokens.filter(t=>bt.includes(t)).length-tokens.filter(t=>at.includes(t)).length})[0];const img=page?.imageinfo?.[0],found=img?.thumburl||img?.url||'';photoCache.set(key,found);return found}catch{photoCache.set(key,'');return''}}
function pumpPhotos(){while(photoBusy<3&&photoQueue.length){const img=photoQueue.shift();if(!img||img.dataset.loading==='1'||!img.isConnected)continue;img.dataset.loading='1';photoBusy++;const r=animeRows().find(x=>String(x.id)===String(img.dataset.animeId));(r?resolvePhoto(r):Promise.resolve('')).then(src=>{if(src&&img.isConnected){img.src=src;img.addEventListener('load',()=>img.closest('.anime-card-thumb')?.classList.add('has-photo'),{once:true})}}).finally(()=>{photoBusy--;pumpPhotos()})}}
const photoObserver='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){photoObserver.unobserve(e.target);photoQueue.push(e.target);pumpPhotos()}}),{rootMargin:'240px'}):null;
function observeAnimePhotos(){grid.querySelectorAll('[data-anime-photo]:not([data-photo-watch])').forEach(img=>{img.dataset.photoWatch='1';photoObserver?photoObserver.observe(img):(photoQueue.push(img),pumpPhotos())})}
function addFact(gridEl,label,value){if(!value)return;const d=document.createElement('div'),s=document.createElement('small'),b=document.createElement('b');s.textContent=label;b.textContent=value;d.append(s,b);gridEl.append(d)}
function enhanceDetail(){if(!detail||detail.querySelector('.anime-source-card')||detail.querySelector('.cook-mode'))return;const marker=detail.querySelector('[data-detail-fav]');if(!marker)return;const r=animeRows().find(x=>String(x.id)===String(marker.dataset.detailFav));if(!r)return;const card=document.createElement('div');card.className='anime-source-card';const h=document.createElement('div');h.className='anime-source-title';h.innerHTML=`<span>📺</span><div><small>From anime</small><b>${esc(r.animeSeries||'Anime')}</b></div>`;const facts=document.createElement('div');facts.className='anime-source-grid';addFact(facts,'Episode',[r.animeEpisode,r.animeEpisodeTitle].filter(Boolean).join(' · '));addFact(facts,'Anime dish',r.animeDishName);addFact(facts,'Real-world version',r.realWorldDish);addFact(facts,'Recreation',r.adaptationType);card.append(h,facts);detail.querySelector('.recipe-facts')?.insertAdjacentElement('afterend',card);const source=detail.querySelector('.source-disclosure>div');if(source&&!source.querySelector('.anime-reference-copy')){const ref=document.createElement('div');ref.className='anime-reference-copy';ref.innerHTML=`<p><b>Anime:</b> ${esc(r.animeSeries||'')}</p>${r.animeEpisode?`<p><b>Episode:</b> ${esc(r.animeEpisode)}${r.animeEpisodeTitle?` · ${esc(r.animeEpisodeTitle)}`:''}</p>`:''}<p><b>Dish shown/referenced:</b> ${esc(r.animeDishName||r.title)}</p><p><b>Bento recreation:</b> ${esc(r.realWorldDish||r.title)}${r.adaptationType?` · ${esc(r.adaptationType)}`:''}</p>`;source.append(ref)}}
function schedule(){requestAnimationFrame(()=>{enhanceCuisines();if(animeTab?.classList.contains('active'))renderAnime();else if(filters)filters.style.display='';enhanceDetail()})}
new MutationObserver(()=>{if(animeTab?.classList.contains('active')&&!renderingAnime)schedule()}).observe(grid,{childList:true});new MutationObserver(()=>{enhanceCuisines();if(animeTab?.classList.contains('active'))schedule()}).observe(panel,{childList:true,subtree:true});if(detail)new MutationObserver(enhanceDetail).observe(detail,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('[data-recipe-browse]')){animeLimit=30;setTimeout(schedule,0)}const more=e.target.closest('[data-anime-more]');if(more){animeLimit+=30;renderAnime()}},true);let searchTimer;if(search)search.addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(queryIsAnime(search.value)&&!animeTab?.classList.contains('active'))animeTab?.click();if(animeTab?.classList.contains('active')){animeLimit=30;renderAnime()}},90)},true);if(sort)sort.addEventListener('change',()=>{if(animeTab?.classList.contains('active')){animeLimit=30;renderAnime()}},true);schedule();
})();
