'use strict';
const fs=require('fs'),vm=require('vm');
const index=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8'),sw=fs.readFileSync('service-worker.js','utf8');
const srcs=[...index.matchAll(/<script[^>]+src=["']([^"']+)["'][^>]*>/g)].map(m=>m[1].split('?')[0]).filter(s=>s.startsWith('data/')&&s.endsWith('.js'));
const c={console,URL,URLSearchParams,TextDecoder,TextEncoder,atob,btoa,Math,Date,Set,Map,WeakSet,WeakMap,Array,Object,String,Number,Boolean,RegExp,JSON,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent};c.window=c;c.globalThis=c;vm.createContext(c);
for(const f of srcs){if(!fs.existsSync(f))throw new Error(`Missing index data script ${f}`);vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f,timeout:5000})}
const lib=c.BENTO_RECIPE_LIBRARY||[],photos=c.BENTO_RECIPE_PHOTO_INDEX||{};
const isAnime=r=>!!r.animeSeries,isGenshin=r=>r.gameSeries==='Genshin Impact'||r.collection==='Genshin Impact'||!!r.gameDish,isStandard=r=>!isAnime(r)&&!isGenshin(r);
const scopes={Japanese:lib.filter(r=>isStandard(r)&&r.cuisine==='Japanese'),Filipino:lib.filter(r=>isStandard(r)&&r.cuisine==='Filipino'),Korean:lib.filter(r=>isStandard(r)&&r.cuisine==='Korean'),Chinese:lib.filter(r=>isStandard(r)&&r.cuisine==='Chinese'),Thai:lib.filter(r=>isStandard(r)&&r.cuisine==='Thai'),Genshin:lib.filter(isGenshin),Anime:lib.filter(isAnime)};
const expected={Japanese:149,Filipino:164,Korean:174,Chinese:40,Thai:60,Genshin:372,Anime:99};
const fails=[];const fail=(id,msg)=>fails.push(`${id}: ${msg}`);
if(lib.length!==1058)fail('library',`expected 1058 recipes, got ${lib.length}`);const ids=new Set();for(const r of lib){const id=String(r?.id||'');if(!id)fail('library','recipe with missing id');else if(ids.has(id))fail(id,'duplicate id');ids.add(id)}
for(const [k,n] of Object.entries(expected))if(scopes[k].length!==n)fail(k,`expected ${n}, got ${scopes[k].length}`);
const expectedAllergens=ings=>{const raw=(' '+(ings||[]).join(' ')+' ').toLowerCase(),out=[];const add=x=>{if(!out.includes(x))out.push(x)};if(/\b(soy sauce|tamari|miso|tofu|soybean|soybeans|edamame|soy milk|doubanjiang|gochujang|doenjang|fermented bean paste)\b/.test(raw))add('soy');if(/\b(wheat|all-purpose flour|bread flour|cake flour|tempura flour|panko|breadcrumbs?|bread crumbs?|ramen|udon|soba|wheat noodles?|egg noodles?|spaghetti|pasta|gyoza wrappers?|dumpling wrappers?|wonton wrappers?|spring roll wrappers?|soy sauce|hoisin sauce)\b/.test(raw))add('gluten');if(/\b(egg|eggs|egg yolks?|egg whites?|mayonnaise|mayo|hollandaise)\b/.test(raw))add('egg');const dairy=raw.replace(/\b(coconut|soy|almond|oat|rice|cashew|macadamia) milk\b/g,' plantmilk ');if(/\b(whole milk|fresh milk|evaporated milk|condensed milk|buttermilk|cream|heavy cream|whipping cream|butter|cheese|parmesan|mozzarella|cheddar|yogurt|yoghurt|milk powder|powdered milk|ice cream)\b/.test(dairy)||/(^|[^a-z])milk([^a-z]|$)/.test(dairy))add('milk');if(/\b(fish sauce|bonito|katsuobushi|dashi|anchov(?:y|ies)|salmon|tuna|mackerel|cod|sardines?|fish cake|chikuwa|kamaboko|tilapia|bangus|milkfish|sea bass|perch|trout|snapper)\b/.test(raw))add('fish');const shell=raw.replace(/\b(vegetarian|vegan|mushroom) oyster sauce\b/g,' oyster-style-sauce ');if(/\b(shrimp|prawn|crab|clam|mussel|oyster(?:s| sauce)?|scallop|squid|octopus|abalone|lobster)\b/.test(shell))add('shellfish');if(/\b(peanut|peanuts|cashew|cashews|walnut|walnuts|almond|almonds|hazelnut|hazelnuts|pistachio|pistachios|pine nut|pine nuts|chestnut|chestnuts|macadamia)\b/.test(raw))add('nuts');if(/\b(sesame|tahini)\b/.test(raw))add('sesame');if(/\b(coconut|coconut milk|coconut cream)\b/.test(raw))add('coconut');return out};
const timed=/(\d+(?:\.\d+)?)\s*(?:–|-|to)?\s*(\d+(?:\.\d+)?)?\s*(minutes?|mins?|hours?|hrs?|seconds?|secs?)/i,doneness=/until|should be|look for|golden|tender|opaque|crisp|crispy|set\b|glossy|reduced|thicken|browned|bubbl|translucent|aromatic|fragrant|puffed|firm|soft|juicy|internal temperature|thermometer|al dente|no raw|cooked through|springy|chewy|elastic|resilient|mushy|rubbery|watery|dry threads/i;
const badGeneric=/prepare and measure all ingredients|combine the main components evenly|cook until hot, browned, and set as appropriate|serve hot with a simple dipping sauce/i;
const proteinIngredient=/\b(chicken|beef|pork|fish|shrimp|prawn|squid|octopus|tofu|egg|duck|lamb|goat|anchovy|mackerel|cod|tuna|salmon|sausage|spam|fish cake|eomuk|sundae)\b/i,meatIngredient=/\b(chicken|beef|pork|duck|lamb|goat|meat|sausage|spam)\b/i;
for(const [scope,rows] of Object.entries(scopes)){
 const methodGroups=new Map();let maxSteps=0;
 for(const r of rows){const id=r.id,title=r.title||id,ings=Array.isArray(r.ingredients)?r.ingredients:[],steps=Array.isArray(r.steps)?r.steps:[],text=steps.join(' '),ingText=ings.join(' '),declared=new Set((r.allergens||[]).map(x=>String(x).toLowerCase()));maxSteps=Math.max(maxSteps,steps.length);
  if(!title.trim())fail(id,'missing title');if(!Number.isFinite(Number(r.servings))||Number(r.servings)<1)fail(id,'invalid recommended servings');
  const prep=Number(r.prep),cook=Number(r.cook),total=Number(r.total);if(![prep,cook,total].every(Number.isFinite)||prep<0||cook<0||total<prep+cook)fail(id,`invalid prep/cook/total ${r.prep}/${r.cook}/${r.total}`);
  if(!String(r.equipment||'').trim())fail(id,'missing equipment');if(!String(r.notes||'').trim())fail(id,'missing recipe details/note');if(ings.length<2)fail(id,'incomplete ingredient list');if(steps.length<3)fail(id,'incomplete method');if(steps.some(s=>badGeneric.test(String(s))))fail(id,'placeholder-like generic method');
  if(cook>=10&&!steps.some(s=>timed.test(String(s))))fail(id,'cook time >=10 min but no explicit timed step');if(cook>=5&&!/drinks?|beverages?/i.test(String(r.category||''))&&!steps.some(s=>doneness.test(String(s))))fail(id,'no doneness/texture cue');
  for(const a of expectedAllergens(ings))if(!declared.has(a))fail(id,`missing allergen ${a}`);
  const refs=[...(Array.isArray(r.sourceUrls)?r.sourceUrls:[])];if(Array.isArray(r.gameAppearances))for(const g of r.gameAppearances||[])if(Array.isArray(g?.sourceUrls))refs.push(...g.sourceUrls);if(!String(r.source||'').trim()||!refs.some(u=>/^https?:\/\//.test(String(u))))fail(id,'missing accuracy/reference metadata');
  if(isStandard(r)&&!(photos[id]||(r.photoQueries||[]).length))fail(id,'missing recipe photo metadata');if(isAnime(r)&&!r.animeSeries)fail(id,'missing anime source metadata');if(isGenshin(r)&&!(r.gameSeries||r.gameDish||r.collection==='Genshin Impact'))fail(id,'missing Genshin source metadata');
  if(/\bthe protein\b|\breturn the protein\b/i.test(text)&&!proteinIngredient.test(ingText))fail(id,'method refers to protein but ingredients contain no protein');if(/\bmeat browns\b|\braw meat\b/i.test(text)&&!meatIngredient.test(ingText))fail(id,'method refers to meat but ingredients contain no meat');
  if(/\bmushrooms?\b/i.test(text)&&!(/\bmushrooms?\b/i.test(ingText))&&/stir-fry|saut[eé]|cook|add/i.test(text))fail(id,'method cooks mushrooms that are not in ingredients');
  if(steps.length){const key=JSON.stringify(steps);if(!methodGroups.has(key))methodGroups.set(key,[]);methodGroups.get(key).push(id)}
 }
 if(maxSteps<=6)fail(scope,`possible artificial method cap; max step count ${maxSteps}`);
 for(const group of methodGroups.values())if(group.length>1){const allowed=scope==='Genshin'&&group.some(id=>/_ch_/.test(id));if(!allowed)fail(scope,`unrelated exact duplicate method group: ${group.join(', ')}`)}
}
if(c.BENTO_RECIPE_QUALITY_VERSION!==27)fail('system','recipe-quality-runtime v27 not executed');
if(!/recipeDetailServingTarget=clamp\(Number\(servingTarget\)\|\|Number\(r\.servings\)\|\|2,1,30\)/.test(app))fail('system','recommended serving is not the default');
if(!/keepUntilDouble[\s\S]{0,220}f<2/.test(app))fail('system','smart salt/seasoning scaling missing');
if(!/if\(plan\.special==='genshin'\)return await genshinArtworkSearch\(plan\);if\(plan\.special==='anime'\)return await animeArtworkSearch\(plan\)/.test(app))fail('system','Genshin/Anime can fall through to IRL food photos');
for(const f of ['data/recipe-content-fixes-standard.js','data/recipe-content-fixes-genshin.js','data/recipe-content-fixes-anime.js','data/recipe-quality-runtime.js']){if(!index.includes(f))fail('index',`missing ${f}`);if(!sw.includes(f))fail('service-worker',`not cached: ${f}`)}
if(!/ASSET_VERSION='24p2'/.test(sw)||!index.includes('?v=24p2'))fail('pwa','asset version mismatch');
const duplicateScripts=srcs.filter((x,i,a)=>a.indexOf(x)!==i);if(duplicateScripts.length)fail('index',`duplicate data scripts ${[...new Set(duplicateScripts)].join(', ')}`);
if(fails.length){console.error(`FINAL RECIPE GATE FAILED: ${fails.length}`);for(const x of fails)console.error('FAIL',x);process.exit(1)}
console.log('FINAL RECIPE GATE PASS');console.log(JSON.stringify({recipes:lib.length,counts:Object.fromEntries(Object.entries(scopes).map(([k,v])=>[k,v.length])),qualityVersion:c.BENTO_RECIPE_QUALITY_VERSION,assetVersion:'24p2'},null,2));
