'use strict';
const fs=require('fs'),vm=require('vm'),genshin=require('genshin-db');
const index=fs.readFileSync('index.html','utf8');
const srcs=[...index.matchAll(/<script[^>]+src=["']([^"']+)["'][^>]*>/g)].map(m=>m[1].split('?')[0]).filter(s=>s.startsWith('data/')&&s.endsWith('.js'));
const c={console,URL,URLSearchParams,TextDecoder,TextEncoder,atob,btoa,Math,Date,Set,Map,WeakSet,WeakMap,Array,Object,String,Number,Boolean,RegExp,JSON,parseInt,parseFloat,isNaN,encodeURIComponent,decodeURIComponent};c.window=c;c.globalThis=c;vm.createContext(c);for(const f of srcs)vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f,timeout:5000});
const rows=(c.BENTO_RECIPE_LIBRARY||[]).filter(r=>r.gameSeries==='Genshin Impact'||r.collection==='Genshin Impact'||r.gameDish);
const norm=s=>String(s||'').toLowerCase().replace(/[“”"'’‘]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const sourceById={},missing=[],mismatched=[];
for(const r of rows){let food;try{food=genshin.foods(r.title,{matchCategories:false})}catch{};if(!food){missing.push({id:r.id,title:r.title});continue}if(norm(food.name)!==norm(r.title)){mismatched.push({id:r.id,title:r.title,matched:food.name});continue}sourceById[r.id]={name:food.name,foodtype:food.foodtype,basedish:food.basedish||'',ingredients:(food.ingredients||[]).map(x=>({name:x.name,count:x.count})),url:food.url?.fandom||''};}
const practicalGroups=new Map();for(const r of rows){const key=JSON.stringify(r.ingredients||[]);if(!practicalGroups.has(key))practicalGroups.set(key,[]);practicalGroups.get(key).push(r)}
const collisions=[];for(const group of practicalGroups.values()){const nonSpecial=group.filter(r=>sourceById[r.id]?.foodtype!=='SPECIALTY');if(nonSpecial.length<2)continue;const sigs=new Map();for(const r of nonSpecial){const s=sourceById[r.id];if(!s)continue;const sig=JSON.stringify((s.ingredients||[]).map(x=>`${x.name}:${x.count}`).sort());if(!sigs.has(sig))sigs.set(sig,[]);sigs.get(sig).push(r)}if(sigs.size>1)collisions.push({recipes:nonSpecial.map(r=>({id:r.id,title:r.title,sourceIngredients:sourceById[r.id]?.ingredients||[],practicalIngredients:r.ingredients})),distinctGameIngredientSets:sigs.size});}
const specialtyProblems=[];for(const r of rows){const s=sourceById[r.id];if(!s||s.foodtype!=='SPECIALTY'||!s.basedish)continue;const base=rows.find(x=>norm(x.title)===norm(s.basedish));if(!base)specialtyProblems.push({id:r.id,title:r.title,basedish:s.basedish,problem:'base dish missing from Bento Genshin library'});}
const report={genshinDbVersion:genshin.version,recipeCount:rows.length,exactSourceMatches:Object.keys(sourceById).length,missing,mismatched,specialtyProblems,practicalIngredientCollisions:collisions};fs.mkdirSync('qa-out',{recursive:true});fs.writeFileSync('qa-out/genshin-identity-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify({genshinDbVersion:report.genshinDbVersion,recipeCount:report.recipeCount,exactSourceMatches:report.exactSourceMatches,missing:missing.length,mismatched:mismatched.length,specialtyProblems:specialtyProblems.length,practicalIngredientCollisions:collisions.length},null,2));for(const x of collisions){console.log('\nCOLLISION');for(const r of x.recipes)console.log(r.id,r.title,'GAME=',JSON.stringify(r.sourceIngredients),'BENTO=',JSON.stringify(r.practicalIngredients))}if(collisions.length||specialtyProblems.length)process.exitCode=1;
